### PR TITLE
Type Definitions for Azure DocumentDB Node SDK

### PR DESCRIPTION
**Pull request by alexeldeib**
**Typings URL:** https://github.com/alexeldeib/typed-documentdb

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [X] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [X] Are they external or global modules according the source (e.g. see README sources)?

This is a major update to the Definitely Typed DocumentDB type definitions. It's not complete yet, but has type definitions for almost all of the 1.8.0 (current) version of the SDK (sorry for spamming PRs).

### CODE REVIEW

**Comment by blakeembrey** [comment]
@alexeldeib Could you please try to avoid closing and opening pull requests. It's creates a lot of noise for everyone watching the repo. You can always update a branch and it'll be automatically reflected in GitHub.

**Comment by alexeldeib** [comment]
Apologies, on my end they weren't showing as successfully created for some
reason.

On Tuesday, June 21, 2016, Blake Embrey <notifications@github.com> wrote:

> @alexeldeib <https://github.com/alexeldeib> Could you please try to avoid
> closing and opening pull requests. It's creates a lot of noise for everyone
> watching the repo. You can always update a branch and it'll be
> automatically reflected in GitHub.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/typings/registry/pull/578#issuecomment-227626342>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGfF2cmOpdlgqiENbRp27XAvHn_Ogtwbks5qOJ1FgaJpZM4I7UW4>
> .
>


-- 

Alexander Eldeib

**Comment by blakeembrey** [comment]
Looks great, cheers! One thing, you may want to delete: https://github.com/alexeldeib/typed-documentdb/blob/master/index.d.ts#L2?

**Comment by alexeldeib** [comment]
Ah, missed that one when I started updating the DT definitions, thanks!

**Pull request merged**
