### PR TITLE
Maintenence update

### PR DESCRIPTION
**Pull request by andrew-w-ross**
Just updating the definitions for expect as there were a couple of errors. Updating the react dependency for expect-jsx and made redux no longer a ambient.

### CODE REVIEW

**Comment by unional** [comment]
@andrew-w-ross , a "btw suggestion":

You can rebase your branch to the master so that the PR will consist of only 1 commit. :rose:

**Comment by andrew-w-ross** [comment]
@unional  Ok, do you need to merge before accepting the pr?

**Comment by unional** [comment]
It will be up to @blakeembrey. :rose:

**Comment by blakeembrey** [comment]
I'm happy, cheers! :smile: If you're interested in learning git workflow to avoid with other projects, just let me know @andrew-w-ross

**Comment by andrew-w-ross** [comment]
@blakeembrey I didn't know I was doing it wrong. I'd appreciate If you could send along any materials to help make my future pr's better. Thanks

**Comment by blakeembrey** [comment]
I wrote this a few years ago: http://blakeembrey.com/articles/2013/04/contributing-to-open-source/

**Pull request merged**
