### PR TITLE
Adding typings for primus.

### PR DESCRIPTION
**Pull request by dercodebearer**
Resolves issue #152

### CODE REVIEW

**Comment by blakeembrey** [comment]
@dercodebearer Typings for NPM must be external modules, not ambient. To make it work, it's mostly just pulling what's in `declare module "..."` outside.

**Comment by dercodebearer** [comment]
@blakeembrey Happy to make the change, but here's what I'm noticing. And btw, this might totally be my misunderstanding typescript definitions.

I changed my file to look like this:

```
declare namespace primus {
  export class Primus {
    socket: Socket;
    static connect(url: string, options?: IPrimusConnectOptions): Primus;
    constructor();
    constructor(server: http.Server, options?: IPrimusOptions);
    library(): void;
    open(): void;
    write(data: any): void;
    on(event: string, cb: (spark: ISpark) => void): void;
    end(): void;
    destroy(): void;
    emits(event: string, parser: (next: any, parser: any) => void): void; // might be better tied to a TSD for https://github.com/primus/emits
    id(cb: (id: any) => void): void;
    createSocket(options?: IPrimusOptions): Socket;
    authorize(req: http.ClientRequest, done: () => void): void;
    forEach(cb: (spark: ISpark, id: string, connections: any) => void): void;
    before(event: string, cb: () => void): void;
    before(event: string, cb: (req: http.ClientRequest, res: http.ServerResponse) => void): void;
    before(event: string, cb: (req: http.ClientRequest, res: http.ServerResponse, next: any) => void): void;
    remove(name: string): void;
    enable(name: string): void;
    disable(name: string): void;
    use(name: string, plugin: Object): void;
    transform(event: string, cb: (packet: any) => void): void;
    transforms(event: string, parser: (packet: any, next: any) => void): void; // might be better tied to a TSD for https://github.com/primus/emits
  }

  export interface IPrimusOptions {
    authorization?: Function;
    pathname?: string;
    parser?: string;
    transformer?: string;
    plugin?: Object;
    timeout?: number;
    global?: string;
    compression?: boolean;
    origins?: string;
    methods?: string;
    credentials?: boolean;
    maxAge?: string;
    headers?: boolean;
    exposed?: boolean;
    strategy?: any;
  }

  export interface IPrimusConnectOptions {
    timeout?: number;
    ping?: number;
    pong?: number;
    strategy?: string;
    manual?: boolean;
    websockets?: boolean;
    network?: boolean;
    transport?: any;
    queueSize?: any;
    reconnect?: {
      max?: any;
      min?: number;
      retries?: number;
      factor?: number;
    };
  }

  export interface ISpark {
    headers: any[];
    address: string;
    query: string;
    id: string;
    request: http.ClientRequest;

    write(data: any): void;
    end(data?: any, options?: Object): void;
    emits(event: string, parser: (next: any, parser: any) => void): void; // might be better tied to a TSD for https://github.com/primus/emits
    on(event: string, cb: (data: any) => void): void;
  }
}

export = primus;
```

At which point, all of visual studio code, and typescript begins to complain with this weird, cryptic error:

" Exported variable 'primus' has or is using name 'Primus' from external module "primus" but cannot be made." Was wondering what this error means or what I'm doing wrong.

**Comment by blakeembrey** [comment]
Sorry for the delay, let's try something more like:

```ts
import http = require('http')
import net = require('net')

declare class Primus {
  socket: net.Socket;
  static connect(url: string, options?: Primus.PrimusConnectOptions): Primus;
  constructor();
  constructor(server: http.Server, options?: Primus.PrimusOptions);
  library(): void;
  open(): void;
  write(data: any): void;
  on(event: string, cb: (spark: Primus.Spark) => void): void;
  end(): void;
  destroy(): void;
  emits(event: string, parser: (next: any, parser: any) => void): void; // might be better tied to a TSD for https://github.com/primus/emits
  id(cb: (id: any) => void): void;
  createSocket(options?: Primus.PrimusOptions): net.Socket;
  authorize(req: http.ClientRequest, done: () => void): void;
  forEach(cb: (spark: Primus.Spark, id: string, connections: any) => void): void;
  before(event: string, cb: () => void): void;
  before(event: string, cb: (req: http.ClientRequest, res: http.ServerResponse) => void): void;
  before(event: string, cb: (req: http.ClientRequest, res: http.ServerResponse, next: any) => void): void;
  remove(name: string): void;
  enable(name: string): void;
  disable(name: string): void;
  use(name: string, plugin: Object): void;
  transform(event: string, cb: (packet: any) => void): void;
  transforms(event: string, parser: (packet: any, next: any) => void): void; // might be better tied to a TSD for https://github.com/primus/emits
}

declare namespace Primus {
  export interface PrimusOptions {
    authorization?: Function;
    pathname?: string;
    parser?: string;
    transformer?: string;
    plugin?: Object;
    timeout?: number;
    global?: string;
    compression?: boolean;
    origins?: string;
    methods?: string;
    credentials?: boolean;
    maxAge?: string;
    headers?: boolean;
    exposed?: boolean;
    strategy?: any;
  }

  export interface PrimusConnectOptions {
    timeout?: number;
    ping?: number;
    pong?: number;
    strategy?: string;
    manual?: boolean;
    websockets?: boolean;
    network?: boolean;
    transport?: any;
    queueSize?: any;
    reconnect?: {
      max?: any;
      min?: number;
      retries?: number;
      factor?: number;
    };
  }

  export interface Spark {
    headers: any[];
    address: string;
    query: string;
    id: string;
    request: http.ClientRequest;

    write(data: any): void;
    end(data?: any, options?: Object): void;
    emits(event: string, parser: (next: any, parser: any) => void): void; // might be better tied to a TSD for https://github.com/primus/emits
    on(event: string, cb: (data: any) => void): void;
  }
}

export = Primus;
```

What do you think?

**Comment by dercodebearer** [comment]
No worries - I've been unable to login at a regular rate either. :(

In any event - I'll check  this out and keep ya posted. Really appreciate the feedback!

**Comment by dercodebearer** [comment]
Okay - I made the change - now tsc cannot find the module.

I'm using es6 style imports, so doing

```
import * as Primus from 'primus'
```

I'm clearly not wrapping my head around the way tsc's expecting the definition to be.

**Comment by blakeembrey** [comment]
@dercodebearer You need to bundle it for `tsc` to find it. Typings takes external modules and wraps them up to make them ambient like your original code. It does this because then we can control the namespacing and versioning properly.

**Comment by unional** [comment]
What you need to do is at your repo folder:
```sh
typings bundle -o <directory>
```

**Comment by dercodebearer** [comment]
Okay - trying this now!

**Comment by dercodebearer** [comment]
Magic! That worked! I wasn't aware of the bundle functionality. Thank you folks. As I stated earlier, pretty new to typings.

So now, I have few questions:

1. Do I simply update my file and issue a new PR, or would you like me to run bundle on it as well?
2. The Primus repo has the old typings file (the one that is on the current PR)- I'm guessing I should add the "typings" field to their package.json and issue a PR? They're pretty new to typescript as well - any help would be appreciated.
3. Again, do I need to run `typings bundle` on that repo?
4. Lastly, when I have dependencies on other typings (there are some primus based libs that I'd like to contribute typings for as well), how do I install all dependencies recursively?

**Comment by blakeembrey** [comment]
> Do I simply update my file and issue a new PR, or would you like me to run bundle on it as well?

Just update the file and issue a new PR.

> The Primus repo has the old typings file (the one that is on the current PR)- I'm guessing I should add the "typings" field to their package.json and issue a PR?

Yes, you can definitely start a conversion in the form of an issue or PR. You can point them to https://github.com/typings/typings/issues/322.

> Again, do I need to run typings bundle on that repo?

You shouldn't need to bundle in any repo, except for when testing. It's just wrapping things up the same way it'll act when people install your typings - so it let's you test if they're correct.

> Lastly, when I have dependencies on other typings (there are some primus based libs that I'd like to contribute typings for as well), how do I install all dependencies recursively?

As long as it's a dependency in `typings.json` or has a `typings` field in `package.json`, they will be resolved automatically.

**Pull request merged**
