### PR TITLE
Add typings for mock-knex

### PR DESCRIPTION
**Pull request by jessezhang91**
**Typings URL:** https://github.com/jessezhang91/typed-mock-knex

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [ ] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
       - single index.d.ts
* [x] Are they external or global modules according the source (e.g. see README sources)?
       - external modules

### CODE REVIEW

**Comment by felixfbecker** [comment]
https://github.com/jessezhang91/typed-mock-knex/blob/master/index.d.ts#L4
Please remove the `declare namespace` and export the symbols directly

**Comment by felixfbecker** [comment]
https://github.com/jessezhang91/typed-mock-knex/blob/master/typings.json#L7-L8
These should not be `devDependencies`

It would be super awesome if you could convert `knex` too, so we get proper dependency management and users don't have to install it manually :)

**Comment by jessezhang91** [comment]
Should those be global dependencies?

**Comment by felixfbecker** [comment]
`node` yes. `knex` unfortunately too, because all typings from DT are "global" by nature. Which is why it would be nice to have `knex` in the registry aswell, because otherwise users have to install it manually.

**Comment by felixfbecker** [comment]
https://github.com/jessezhang91/typed-mock-knex/blob/master/index.d.ts#L1
This should be `import knex = require('knex')`

**Comment by jessezhang91** [comment]
Gotcha. I'll try to convert the `knex` typings over some time soon.

**Comment by jessezhang91** [comment]
Alright, I've made the dependency and require changes. Thanks!

**Comment by felixfbecker** [comment]
Nice :)

**Pull request merged**
