### PR TITLE
Update with PR requested by @unional

### PR DESCRIPTION
**Pull request by shawnlauzon**
**Typings URL:** https://github.com/shawnlauzon/typed-soundcloud

**Questions (for new typings):**

* [ ] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [ ] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [ ] Are they external or global modules according to the source (e.g. see README sources)?

**Change Summary (for existing typings):**

From @unional's PR:

> Refactored the code.
> Also fixed the jspm test. I need to make some changes to generator-typings

### CODE REVIEW

**Comment by felixfbecker** [comment]
Why not do the typings ES6-style?
```ts
import { Promise } from 'es6-promise';
export function initialize(options: SoundCloud.InitializeOptions);
export function connect(options?: SoundCloud.ConnectOptions): Promise<any>;

export function get(path: string, params?: any): Promise<any>;
export function post(path: string, params?: any): Promise<any>;
export function put(path: string, params?: any): Promise<any>;
export function delete(path: string): Promise<any>;

export function upload(options: any): Promise<any>;
export function resolve(url: string): Promise<any>;
export function oEmbed(url: string, params?: any): Promise<any>;

export function stream(trackPath: string, secretToken?: string): Promise<SoundCloud.Player>;

export interface InitializeOptions {
    client_id: string;
    redirect_uri?: string;
    oauth_token?: string;
  }

export interface ConnectOptions {
    client_id: string;
    redirect_uri: string;
    scope?: string;
  }

 export interface Player {
    play();
    pause();
    seek(time: number);
    currentTime(): number;
    setVolume(volume: number);
    getVolume(): number;
    on(event: string, handler: any);
  }
}
```

**Comment by felixfbecker** [comment]
Also, `Player.play()` and others are missing a return type annotation - this will cause compilation errors with `noImplicitAny`. You should add that option to tsconfig.json

**Comment by unional** [comment]
This was done quite a while ago. Yes, `Player.play()` and others can add the return type.
As for ES6 vs CommonJS, I think either is fine, but my general suggestion is to keep the typings the same as what the source is to avoid any interop confusion.

**Comment by shawnlauzon** [comment]
Sounds good. I'll add those return types and add `noImplicitAny` to tsconfig.json. As @unional suggests, I'll leave the others as they are.

**Pull request merged**
