### PR TITLE
Add type definitions for i2c-bus

### PR DESCRIPTION
**Pull request by 101100**
**Typings URL:** https://github.com/101100/typed-i2c-bus

**Questions (for new typings):**

* [X] Does the README explain the purpose and a link to the typed source?
* [X] Do the typings follow the source structure?
* [X] Are they correctly external or ambient modules?

### CODE REVIEW

**Comment by 101100** [comment]
The typing uses `Buffer`, but I didn't want to tie to any particular version of node.js.  How should I handle that?

**Comment by blakeembrey** [comment]
Just use `Buffer`, it's fine. If you want, list node as an ambient dependency and it'll warn for you.

Aside from that, make sure the definition is in external module format. E.g. remove `declare 'x'` (https://github.com/101100/typed-i2c-bus/blob/master/i2c-bus.d.ts#L5).

**Comment by 101100** [comment]
I've removed the `declare` wrapper.

How would I mark node as an ambient dependency?

**Comment by blakeembrey** [comment]
@101100 You can do `typings install env!node --save --ambient` to install the ambient node typings. That really just creates an entry in `typings.json` for you and the key is what really matters in the warning.

**Comment by 101100** [comment]
OK, I understand now, I think.  I've added a note to the `README.md` that the user will need the node ambient typings installed.

Ready for another look.

**Pull request merged**
