### PR TITLE
Added the version 1.10.1 of oracledb to typings registry.

### PR DESCRIPTION
**Pull request by Bigous**
**Typings URL:** https://github.com/Bigous/typed-oracledb

**Questions (for new typings):**

* [X] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [X] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [X] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**

### CODE REVIEW

**Comment by unional** [comment]
Two things I spotted:

- You are using `stream`, so should list `node` as `globalDependencies` instead of `globalDevDependencies`
- Since you are simply exporting the whole namespace, you can export what's inside the namespace directly with ES2015 named export syntax.

**Comment by Bigous** [comment]
Hi @unional ,
First point you are correct! Done.
The second one I didn't get. Why is it better export each item on namespace than export the whole namespace (I'm doing it in DefinitelyTyped, but I thought that exporting the namespace would be more interesting - less typing)?

**Comment by unional** [comment]
Second point allows user to import using both commonjs and ES2015 in a more consistent way, relying on ES2015 -> CommonJS interop.

The other way relies on CommonJS -> ES2015 interop is more problematic (due to differences between `SystemJS` and `Babel`)

It is a minor difference, but the ES2015 named export is the preferred approach, in general.

Of course, that would be a debate on whether the typings should stay true to the source. So the counter argument is whether if the source is written in ES2015 or not.

The final choice would be up to you. 🌷

**Comment by unional** [comment]
cc/ @blakeembrey if there is something I missed or made incorrect statements 🌷

**Comment by blakeembrey** [comment]
Looks correct 👍 In the end it makes little difference. You do that on DefinitelyTyped because you have to - there's no external modules (in the past), so you'd make a namespace to expose things globally and allow others to extend it. It's not super important and I think it's good either way, we just tend to promote using ES6-style `export function foo` instead of `namespace X { export function foo } export = X` as it's more natural and generally how the original author intended it.

**Comment by Bigous** [comment]
Just for the record - the generator-typings (which I used here to make things happen faster) creates a index.d.ts with the following content:
```typescript
declare module xxxx {
}
export = xxxx;
```
It induced me to write that way.

But now I've got the point - next version I'll use the ES6 approach.

**Comment by unional** [comment]
Yup. That's the template for commonjs modules. Because they can have function + namespace structure.

**Comment by blakeembrey** [comment]
No worries. Thanks for your contribution 😄 I'll stop pointing it out from now on, I'm happy with either style.

**Pull request merged**
