### PR TITLE
Create node-localstorage.json

### PR DESCRIPTION
**Pull request by pellejacobs**
**Typings URL:** https://github.com/pellejacobs/typed-node-localstorage

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [ ] Are they external or global modules according the source (e.g. see README sources)?
No.

### CODE REVIEW

**Comment by unional** [comment]
Can you add a link to the source in either README or repo description?
That would help us a lot in verifying the typings.
For example:
https://github.com/types/npm-bluebird

**Comment by pellejacobs** [comment]
Must have disappeared cleaning the readme, sorry. Should be fine now!

**Comment by unional** [comment]
Seems like markdown does not recognize `git+ssh://`. 

btw, how did you put that in through the generator? You typed the repo url in that manually?

**Comment by pellejacobs** [comment]
I can reproduce it, just using yo, with `CommonJS Module` and `Native NodeJS`.  ¯\_(ツ)_/¯

**Comment by unional** [comment]
I see. A bug to fix. It gets it from `npm info node-localstorage`:

```sh
...
repository:
   { type: 'git',
     url: 'git+ssh://git@github.com/lmaccherone/node-localstorage.git' },
...
```
I'll fix it in 2.0

**Pull request merged**
