### PR TITLE
Added TimeCircles typings

### PR DESCRIPTION
**Pull request by kristoftorfs**
**Typings URL:** https://github.com/kristoftorfs/typed-timecircles

**Questions (for new typings):**

* [X] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
  * they are in a single file
* [X] Are they external or global modules according the source (e.g. see README sources)?
  * global

### CODE REVIEW

**Comment by felixfbecker** [comment]
The package.json name is just `timecircles`, the JSON file should have the same name

**Comment by kristoftorfs** [comment]
Do you mean the typings.json file?

**Comment by felixfbecker** [comment]
No the file you created in this PR

**Comment by kristoftorfs** [comment]
Renamed the file

**Comment by felixfbecker** [comment]
LGTM

**Pull request merged**
