### PR TITLE
Added jsonapi-datastore.json.

### PR DESCRIPTION
**Pull request by EricPMulligan**
**Typings URL: **
https://github.com/EricPMulligan/typed-jsonapi-datastore

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

### CODE REVIEW

**Comment by unional** [comment]
Great.  Do you want to consider removing `declare module "..." {` and make it an external module instead? That way you can add two json files: `registry/npm/jsonapi-datastore.json` and `registry/bower/jsonapi-datastore.json`
and user can install it by `typings install jsonapi-datastore` or `typings install bower~jsonapi-datastore` instead.

If not, you need to add `typings.json/global: true` in your `typings.json`.

**Comment by EricPMulligan** [comment]
This is my first ever contribution to any open source project so any feedback is greatly appreciated!

I just moved it to registry/npm/jsonapi-datastore.json. Am I supposed to create a new directory for bower? I'm only asking because there's presently no registry/bower directory in this repo.

**Comment by blakeembrey** [comment]
@EricPMulligan Yes, you're welcome to create a directory for `bower`. You'd be the first to contribute typings for it 😄

**Comment by EricPMulligan** [comment]
Ok, I just created the bower directory and added another jsonapi-datastore.json file to it.

**Comment by unional** [comment]
👍

**Pull request merged**
