### PR TITLE
added tone.js typings

### PR DESCRIPTION
**Pull request by lukephills**

### CODE REVIEW

**Comment by blakeembrey** [comment]
Awesome, cheers! Quick question, is everything in the library always global? Aside from that, I found https://github.com/BlokDust/Tone.js/blob/master/utils/TypeScript/Tone.d.ts. If you don't want to maintain it in two places, you're welcome to point it there instead.

E.g. `github:BlokDust/Tone.js/blob/master/utils/TypeScript/Tone.d.ts#ad623816d5a8d9742bde5fe34f12b24d8e5e5f62`.

**Comment by blakeembrey** [comment]
@lukephills Sorry, I had a typo above. I just corrected it.

**Comment by lukephills** [comment]
Oh that would be good to point it there instead. I'm having trouble though. Any idea what i'm missing?

**Comment by blakeembrey** [comment]
Try the URL I updated in the comment above, I had a typo previously (accidentally left `blob/master/` in the path).

**Comment by lukephills** [comment]
OK great thanks! Everything is written globally like this:

var mod = new Tone.Module();
mod.doSomething();

**Comment by blakeembrey** [comment]
LGTM! :+1: Thanks for contributing.

**Comment by blakeembrey** [comment]
Just FYI, in the future if there's a new folder for "global" dependencies, I'll ping you in case I'm going to be moving it about.

**Comment by lukephills** [comment]
Ok great thanks!

**Pull request merged**
