### PR TITLE
typings for prompt

### PR DESCRIPTION
**Pull request by sinse**
**Typings URL:** https://github.com/sinse/npm-prompt.git

**Questions (for new typings):**

* [X] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [X] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [X] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**

update the git hash registry to the last reference
(after ur changes requests)

### CODE REVIEW

**Comment by felixfbecker** [comment]
Needs rebase

**Comment by sinse** [comment]
hi, first time i use rebase
seems to be good

**Comment by felixfbecker** [comment]
Actually what you did is a merge and not a rebase, but it's fine aswell :D

**Comment by sinse** [comment]
ok, great, thx a lot

**Pull request merged**
