### PR TITLE
Update bluebird.json

### PR DESCRIPTION
**Pull request by louy**
Adding version 3.3.4

### CODE REVIEW

**Comment by unional** [comment]
There is a typo. Also, do you want to update it in https://github.com/typed-typings/npm-bluebird?

**Comment by louy** [comment]
Fixed. Thanks! Well I wouldn't mind, but I've been working on this fork for a long time now. We can probably merge the two. Would you make me a contributor to that repo?

**Comment by unional** [comment]
@blakeembrey , can you add @louy to that repo? Lost ownership when transferred.

**Comment by blakeembrey** [comment]
@louy I'll add you to `typed-typings`. Done.

**Comment by blakeembrey** [comment]
@louy Done. What did you want to do with this PR now?

**Comment by louy** [comment]
I'll update it once github starts working again! thanks.

**Comment by louy** [comment]
@blakeembrey it's updated.

**Comment by unional** [comment]
@Louy seems like you have other commit mixed with this

Also, should the previous version be kept?

**Comment by louy** [comment]
I think squashing would solve this when you merge. You're right about previous version.  Sorry about that.

**Comment by blakeembrey** [comment]
@unional What's the issue with the previous version? I don't see an issue with keeping it around?

**Comment by unional** [comment]
Yes, my point is to keeping it around.

**Comment by blakeembrey** [comment]
Ok, we should keep old versions :smile: The API is currently deprecating dead versions anyway, so if you do that it'll start emitting deprecated notices.

**Comment by unional** [comment]
> so if you do that it'll start emitting deprecated notices.

Which bring up a point that if the user is using a specific version (e.g. `chai@3.4.0`), if `chai@3.5.0` is available would it print the deprecating warning?
I think it should be suppressed.

**Comment by blakeembrey** [comment]
It's not marked as deprecated if you haven't deleted it from the registry, so it would be "suppressed". However, if you delete the version from the registry doesn't that constitute no more support for that version?

**Comment by unional** [comment]
> constitute no more support for that version?

But why? If the typings is correct for that version, I don't see a reason to not support it if the user choose to use that particular version.

**Comment by blakeembrey** [comment]
Because you deleted the version?

**Comment by unional** [comment]
Yup. That's why I don't see much reason in removing entries in `typings/registry`, just like you normally won't `npm unpublish`. :smile:

**Pull request merged**
