### PR TITLE
Added typings-golden-layout

### PR DESCRIPTION
**Pull request by stephenjelfs**

### CODE REVIEW

**Comment by Fank** [comment]
source url and typings url please

**Comment by stephenjelfs** [comment]
@Fank Here are the URLs--please let me know if I also need to commit these somewhere?

The project is golden-layout:
https://www.npmjs.com/package/golden-layout
https://github.com/deepstreamIO/golden-layout

And the typings are here:
https://github.com/Genedata/typings-golden-layout

**Comment by blakeembrey** [comment]
Awesome, cheers! Have you considered using classes for the declarations instead of manual interfaces?

**Comment by stephenjelfs** [comment]
@blakeembrey I replaced the GoldenLayout interface with a class:

[https://github.com/Genedata/typed-golden-layout/commit/972bae8d97678e580986bda305cf73029a67aa7f]

But, I was not sure if you also mean the other interfaces, inside the namespace, because they are not exported?

**Comment by blakeembrey** [comment]
Yes, that's all I was currently referring to.

**Pull request merged**
