### PR TITLE
Update declarations d3-array, d3-axis, d3-color, d3-hierarchy, d3-int…

### PR DESCRIPTION
**Pull request by iamssen**
**Typings URL:** <https://github.com/iamssen/typings-d3>

**Change Summary (for existing typings):**

1. little bug fixes
2. match js libraries version numbers

<https://github.com/iamssen/typings-d3/commit/5f8424f79a47abdef36799e51cc55a6c413af01f>

### CODE REVIEW

**Comment by blakeembrey** [comment]
Wait, quick question - do you want access to @typed-typings and, specifically, the existing D3 typings?

**Comment by iamssen** [comment]
Um... my english is not good. I don't know my understand is exactly about your question.

Your question meaning 
Need I access <https://github.com/typed-typings/npm-d3> this repository?

**Comment by blakeembrey** [comment]
Sorry, yes. Would you like access to that repository to help maintain it? I don't think anyone is particularly maintaining it today, and you seem to be do a lot of work on D3 currently.

**Comment by blakeembrey** [comment]
Do you know if that definition needs updating to 4.0 then?

**Comment by iamssen** [comment]
i think d3 3.x project update to 4.x is not good.
because it is make confuse d3 3.x users.

um... maybe we have 2 choices

- one project
  - 3
    - d3.3.x.d.ts
  - 4
    - selection
    - scale
    - ...


or

- d3-3.x project
  - d3.d.ts
- d3-4.x project
  - ...

i think second is better. npm-d3 project keep for d3 3.x users.

**Pull request merged**
