### PR TITLE
add parseUri typings

### PR DESCRIPTION
**Pull request by effervescentia**
**Typings URL:** https://github.com/effervescentia/typed-parseUri

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

### CODE REVIEW

**Comment by felixfbecker** [comment]
You know about native url.parse right? That module looks horrible - no readme, commited node_modules, test runner as dependency...

**Comment by effervescentia** [comment]
@felixfbecker the typings yeoman generator picked up the wrong npm package. Supposed to target https://www.npmjs.com/package/parseUri. And I know about it, but that doesn't mean I can use it in the browser, whereas I *can* use this

**Comment by felixfbecker** [comment]
@effervescentia there is a port of the native url package for browserify ;)https://www.npmjs.com/package/url

(of course I have no problem with merging this)

**Comment by effervescentia** [comment]
@felixfbecker using webpack not browserify

**Comment by felixfbecker** [comment]
Doesn't matter, you can just add that package as a dependency ;)

**Comment by effervescentia** [comment]
😓 foiled at every turn... It's smaller? Justifiable?

**Comment by felixfbecker** [comment]
Well it has _way_ more downloads so I would say it is way more reliable/smaller/tested

**Comment by effervescentia** [comment]
https://www.npmjs.com/package/url has just under twice as many downloads as https://www.npmjs.com/package/parseUri, which solely encapsulates the functionality of parsing a uri, whereas `url` also has logic for building urls, so I would argue it is demonstrably smaller. Not to mention that `parseUri`s download statistics are not insignificant by any measure.

**Comment by unional** [comment]
I think it's merely a personal choice. If the typings looks fine I think we should merge it. @felixfbecker ok with you?

**Comment by blakeembrey** [comment]
I merged since it all looked good and the suggestions here were the same I'd give anyway, it's a pretty barren library - no README, source code links, docs, etc. If it works, great, but I'd be hesitant to tell anyone else to use it too 😄

**Comment by effervescentia** [comment]
@blakeembrey thanks for merging.
However, it looks like somehow it's pointing at https://www.npmjs.com/package/parseuri instead of https://www.npmjs.com/package/parseUri. Is this because of the file naming (`parseuri.json`)? Or something else? I also see https://www.npmjs.com/package/parseuri as the source when I run `typings search parseuri`. The generated typings also appear to use the module name `parseuri`.

**Comment by blakeembrey** [comment]
Wow, that's confusing. Yeah, it should have been uppercased in the filename. You can submit a PR to correct that.

**Comment by effervescentia** [comment]
ah damn -__- okay cool, thanks

**Comment by unional** [comment]
Yeah. Since you use `generator-typings`, that comes from the source package.json`

**Comment by effervescentia** [comment]
@unional can confirm that it was the file naming in `typings/registry` and nothing else (at least, seeing as everything else was correct)

**Comment by unional** [comment]
I see. You are correct. The `typings.json` looks fine. 
https://github.com/effervescentia/typed-parseUri/blob/master/typings.json

**Comment by effervescentia** [comment]
@blakeembrey kind of odd behaviour though, would have assumed (along with @unional) that the `name` field in `typings.json` would be responsible

**Comment by blakeembrey** [comment]
Nope, sorry. The `name` field in `typings.json` was a later addition - mostly just for logging in the end. I believe the whole project still works without a name at all. The API itself doesn't actually load anything from your definition to serve it, it just provides pointers from a -> b.

**Comment by effervescentia** [comment]
ah, fair enough 👍  thanks

**Pull request merged**
