### PR TITLE
Add type definitions for node-static

### PR DESCRIPTION
**Pull request by effervescentia**
~~**Typings URL:** https://github.com/cloudhead/node-static~~
**Typings URL:** https://github.com/effervescentia/typed-node-static

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

### CODE REVIEW

**Comment by blakeembrey** [comment]
@effervescentia Thanks for the PR! It looks pretty good. I noticed a small typo: https://github.com/effervescentia/typed-node-static/blob/master/index.d.ts#L12. I think it's meant to be `serve`.

**Comment by blakeembrey** [comment]
Let me know about the above change and I can merge. Aside from that, you could also use ES6-style exports here without requiring the namespace.

```ts
export class Server {}
export var version: string
```

**Comment by effervescentia** [comment]
@blakeembrey updated the export style and removed the offending `server` method

**Comment by blakeembrey** [comment]
LGTM 👍

**Pull request merged**
