### PR TITLE
Add typings for Vuex v1.0.0-rc.2

### PR DESCRIPTION
**Pull request by ktsn**
**Typings URL:** https://github.com/vuejs/vuex/tree/master/types

**Questions (for new typings):**

* [ ] Does the README explain the purpose of the typings and have a link to the JavaScript project?
  * The typings is in the JavaScript project
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

### CODE REVIEW

**Comment by blakeembrey** [comment]
@ktsn If you're the author of Vuex, you shouldn't be adding the module to the registry. The typings should be provided as the `typings` field in `package.json` instead - this would allow them to be versioned together, correctly.

**Comment by blakeembrey** [comment]
The module should also be written in external module definition format. I would recommend you get in touch with the module author and try to make it more useful to consumers. In the current form, it's really just more work than it's worth to maintain.

**Comment by ktsn** [comment]
@blakeembrey Thank you for your feedback.
The reason that I wrote the module in `declare module` format is Vuex has `import logger from 'vuex/logger'` import style defined on [this](https://github.com/vuejs/vuex/blob/master/types/index.d.ts#L91)

How do I handle this import style in external module definition format?

**Comment by blakeembrey** [comment]
You can write two definition files and store them alongside the JavaScript files. It would work just the same as though it were originally written in TypeScript.

**Comment by ktsn** [comment]
Oh, I see. I will do that.
Thank you very much for your support!

**Pull request closed without merging**
