### PR TITLE
Add 'preact' typings to global

### PR DESCRIPTION
**Pull request by kruczy**
**Typings URL:** https://github.com/developit/preact/blob/master/src/preact.d.ts

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?

the typings are in the project source
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?

yes, `preact.js` -> `preact.d.ts`
* [x] Are they external or global modules according the source (e.g. see README sources)?

**global**

### CODE REVIEW

**Comment by blakeembrey** [comment]
As the author, it would probably be easier to provide instructions on the README for TypeScript users instead of relying on the registry and a third-party update process that may be out-of-sync. What do you think?

**Comment by kruczy** [comment]
the typings could be referenced in `package.json` `typings` property, the problem here is that these need to be global in 1.8.10 because a global JSX namespace needs to be defined and augmenting global scope from modules does not work there

The situation is different in 2.0 as you can augment global scope in modules but if you add the  `typings` property and anyone with ts 1.8 uses the lib they will get a compile error

That's why I think for 1.8 users a `typings install global~preact --global --save` should be fine
and for ts2 users `typings install preact --save` (ill make a pr for this later unless there is a better way to do it)

of course it would be better to just have a `package.json` entry and have a seamless experiance, though I don't think it is possible in the current state of things (unless I am missing something)

**Comment by blakeembrey** [comment]
It's not just a `typings` field in `package.json` though - you can just provide direction to do `typings install npm:preact/src/preact.d.ts --global` after you've NPM installed. You can also distribute a `typings.json` with `global: true` if needed that will work with `typings install npm:preact`. In this case, you can probably skip Typings altogether by recommending they add it to their project context - E.g. `files` in `tsconfig.json` or using a reference.

**Comment by kruczy** [comment]
hey, could do that `typings install npm:preact` seems fine for now, when TS2 goes stable we could probably put the `typings` prop in `package.json`

**Comment by blakeembrey** [comment]
@kruczy Why can't you just do a `typings` property today then? Nothing there changes with 2.0.

**Comment by kruczy** [comment]
you cannot augment global scope in 1.8 from the module, it will give a compilation error if you try
and the global JSX namespace needs to be augmented to make this work,

another way to do it could be to just expose the types and have the user define the JSX namespace

**Pull request closed without merging**
