### PR TITLE
Add http-server

### PR DESCRIPTION
**Pull request by unional**
For npm:http-server

https://github.com/indexzero/http-server

Am I doing it correctly?

### CODE REVIEW

**Comment by blakeembrey** [comment]
This is amazing, cheers! :+1: 

I'm happy to merge this as is, but in interest of giving feedback I did notice one typo: https://github.com/unional/typed-http-server/blob/master/http-server.d.ts#L6 (you've accidentally typed `header` instead of the plural `headers`).

**Comment by blakeembrey** [comment]
How did you type this BTW? Just going through the source code?

**Comment by unional** [comment]
Yes. Just go through the source code. And try to learn how to create definition for class from `typed-es6-promise`

**Comment by unional** [comment]
And nice catch on the header vs headers!

**Comment by blakeembrey** [comment]
Thanks for contributing, again! This is great :smile:

**Pull request merged**
