### PR TITLE
Packages structure fixes

### PR DESCRIPTION
**Pull request by GiedriusGrabauskas**
**Typings url:** https://github.com/QuatroTypings/npm-react-notification-system
**Fixes for:** https://github.com/typings/registry/pull/531

**Typings url:** https://github.com/QuatroTypings/npm-tsconfig-lint
**Fixes for:** https://github.com/typings/registry/pull/533

**Typings url:** https://github.com/QuatroTypings/npm-tsconfig-glob
**Fixes for:** https://github.com/typings/registry/pull/534

### CODE REVIEW

**Comment by blakeembrey** [comment]
Cheers! 👍 The only other thing I'd consider looking into is how you structure your module and exports. For example: https://github.com/QuatroTypings/npm-tsconfig-lint/blob/master/0.11.0/index.d.ts. Currently you export one member of the namespace, but it's a really inefficient way to write it because no one can access the rest of the module. You might want to use a pattern like: https://github.com/typings/typings/blob/master/docs/examples.md#function--utility. For example:

```ts
declare function tsconfigLint (options: tsconfigLint.Options, errorCallback: tsconfigLint.CallBack): void;

declare namespace tsconfigLint {
    interface Options {
        /**
         * A relative path from cwd to the directory containing a tsconfig.json. If not specified, the '.' is used.
         */
        configPath?: string;

        /**
         * The current working directory, defaults to `process.cwd()`
         */
        cwd?: string;

        /**
         * Whether or not `filesGlob` should be used in place of `files` for determining the files to lint.
         */
        useGlob?: boolean;

        tsconfigOptions?: {
            /**
             * The number of spaces to indent the tsconfig.json
             */
            indent?: number;
        };

        /**
         * A relative path from the configPath to the tslint configuration file.
         */
        tsLintConfigFilePath?: string;
    }

    interface CallBack {
        (err?: Error): void;
    }
}

export = tsconfigLint;
```

With this pattern, people can still use `import x = require('...'); x.Options`.

**Comment by DovydasNavickas** [comment]
What is not nice about the format you've written in https://github.com/typings/registry/pull/534 is that code completion gets polluted with all of the interfaces.

image

We we're looking at this format with @GiedriusGrabauskas, but we thought that the one with `contracts.d.ts` would be a bit cleaner one.

image

And if I understand correctly, what you are saying in https://github.com/typings/registry/pull/520
>No one can import anything from your file this way and that file (`contracts`) does not actually exist.

You are only partly right.

It is true that the file does not exist in the package itself.
But as there are ONLY interfaces in the `contracts.d.ts`, it is not required to exist in the package. Because TypeScript compiler emits `import` (`require`) statements in the compiled code ONLY if something that requires emitting is used from the import.

And in case of module defined in `contracts.d.ts`, it has ONLY interfaces and does not require emitting, which is why TypeScript leaves its import out when compiling.

You can try to compile `test.ts` and see for yourself that there is only `import * as gulp from 'gulp';` emitted and nothing is emitted for line `import * as GulpClient from 'gulp/contracts';`

**Comment by blakeembrey** [comment]
Yes, you're correct - but no one knows to do that and there's no documentation on it.

**Comment by blakeembrey** [comment]
On top of which, if you _really_ wanted to hide the interfaces, you don't need a namespace for that.

**Comment by GiedriusGrabauskas** [comment]
I agree with you, that I should use `declare function` instead of `declare var`.
> ...because no one can access the rest of the module.

I added working sample in test.
[QuatroTypings/npm-tsconfig-lint/test.ts](https://github.com/QuatroTypings/npm-tsconfig-lint/blob/master/0.11.0/test/test.ts)

**Comment by blakeembrey** [comment]
@GiedriusGrabauskas Cheers! Sorry to cause a philosophical debate on this 😄 

I really don't see a big issue with the pollution here. If you had written it in TypeScript, it would be the same, and I think we should be aiming to write it as it would be written in TypeScript - not some hacks to make it "prettier" when really the ordering behaviour could just be changed here to put interfaces toward the bottom. Also, in this module format, the interfaces are only exposed on `x.*` - so it's not pollution the main export of a function.

**Comment by unional** [comment]
@GiedriusGrabauskas I had the same reason, I also wanted to keep the completion clean and simple. But in the end I give in to this statement:

> we should be aiming to write it as it would be written in TypeScript

🌷

**Comment by DovydasNavickas** [comment]
Hopefully there is gonna be more and more things written in TypeScript and we are not gonna have these kind of discussions :clap:

**Pull request merged**
