### PR TITLE
linked typings for archieml

### PR DESCRIPTION
**Pull request by ejmurra**
**Typings URL:** https://github.com/ejmurra/typed-archieml

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

### CODE REVIEW

**Comment by felixfbecker** [comment]
You don't need to `declare namespace`, just export the individual types directly like `export interface ...`

**Comment by ejmurra** [comment]
Thanks for the pointer. I used the typings-generator and selected commonjs, amd, and script tags for how the package can be used and then I used the output that it generated directly. 

It seems there's a [pattern suggested](https://www.typescriptlang.org/docs/handbook/writing-declaration-files.html#global--external-agnostic-libraries) by the Typescript docs which declares a `namespace` and then declares a `module` which exports it.

Which is the preferred way of doing it? Should I just export the interface directly and the function on a `namespace`?

Sorry for the noobiness, this is my first time contributing a type definition. Thanks!

**Comment by felixfbecker** [comment]
That is the example _Global / External-agnostic Libraries_, which means a library that both exports elements and introduces a global namespace. But typings you write for NPM modules _are_ already "external" modules (aka ES6 modules). They don't introduce anything global _unless_ you use a `declare global { ... }` block _or_ set `global: true` in your typings.json. That's why you don't need to use `declare module "package-name"` or a namespace (except in certain cases, but this isn't one).

**Comment by ejmurra** [comment]
That makes sense, thank you!

**Comment by felixfbecker** [comment]
Change the file to
```ts
export interface AmlOptions {
  comments: boolean;
}

export function load(content: string, opts?: AmlOptions): any;
```

**Pull request merged**
