### PR TITLE
Add typed-gulp

### PR DESCRIPTION
**Pull request by unional**
~~Does version `3.8` works?
Original DT file says it is for `Gulp v3.8.x`~~

Ok, Travis answered that question for me. :smile:

### CODE REVIEW

**Comment by blakeembrey** [comment]
Yes, just needs to be the lower semantic version range.

**Comment by blakeembrey** [comment]
Can we avoid merging this until the dependencies are typed too? I'd like to avoid confusing/broken dependency trees existing in the registry.

**Comment by unional** [comment]
Meaning you want `orchestrator` and `node` to be typed first?

**Comment by blakeembrey** [comment]
Just `orchestrator`, that's a dependency. Node is fine as is, that's an ambient dependency (E.g. provided by runtime).

**Comment by unional** [comment]
Ok.

**Comment by unional** [comment]
@blakeembrey , updated dependency. Please check. :smile:

**Comment by unional** [comment]
Fix #78

**Comment by blakeembrey** [comment]
I'm ok with the merge (if you are), but it definitely needs large refactoring to make the type information more useful. Right now you won't be able to access any type information in the exported module.

To make it properly, you'd have to use a namespace or top-level exports.

**Comment by unional** [comment]
Arr... I messed up my `test\tsconfig.json`.  I thought it is working. :sob: 

Should it be something like this?
```ts
namespace gulp {
  export function src() {...}
  export function task() {...}
  ...
}

export = gulp
```

I previously use TS only for ES6 + type system. So I still have a lot to learn on the internal module and namespace. :wink:

**Comment by blakeembrey** [comment]
It's kind of a PITA, but I'm happy to merge actually. I was thinking `class + namespace` to expose the types. The issue with `export =` is that's the only type you'll be able to access, so you need to work around it (with `namespace`). I'll figure out a PR if we get to there :smile:

**Comment by unional** [comment]
Great. 

Currently I see it working (at least partially?):
image

I run `typings i -D file:gulp.d.ts` and see the result in `test/test.ts`

**Pull request merged**
