### PR TITLE
Create html2json.json

### PR DESCRIPTION
**Pull request by unional**
https://github.com/types/html2json

### CODE REVIEW

**Comment by blakeembrey** [comment]
@unional Can we stick with the existing naming scheme until we resolve what to do? 😄

**Comment by unional** [comment]
Anyway to push and get it resolved? If there is a chance to have `types/*` as source of `@types/*`, naming it straight is probably the way to go.
The only question is what to do with non-npm packages, right?
Should not affect naming decision for npm packages, I guess.

**Comment by blakeembrey** [comment]
@unional Push a decision? I don't think it's really needed, there's no relation to the GitHub repo and NPM names, so we don't really need to conflate those and should just stick to keeping things consistent for now. You can do `npm install types/npm-html2json` which installs the module named `@types/html2json`. I'd like to keep it consistent since we have various packages in there are may event have none types as we go (E.g. with https://github.com/types/guidelines).

**Comment by unional** [comment]
True. Ok. 🌷

**Comment by unional** [comment]
Speaking of which, maybe the current scheme can be proposed to type-publisher?

**Comment by blakeembrey** [comment]
Which is the current scheme you refer to? Just curious for your take on what the proposal would be - e.g. renaming on NPM or GitHub?

**Comment by unional** [comment]
As is. Github: `types/<source>-<pkg>`.
For npm package, `types/npm-<pkg>` maps to `@types/<pkg>` (and should not be `@types/npm-<pkg>` to avoid confusion in the npm ecosystem).

For other packages, we can do `types/env-<pkg>` maps to `@types/env-<pkg>` or just decide their scheme in the future.

**Comment by blakeembrey** [comment]
Ah, ok. I think we just map it all onto `@types` for now and hope there's no conflict to mirror TS 2.0 + DefinitelyTyped. So that would be `@types/<pkg>` in both cases.

**Pull request merged**
