### PR TITLE
Create mongoose.json

### PR DESCRIPTION
**Pull request by louy**
**Typings URL:** https://github.com/louy/typed-mongoose

**Questions (for new typings):**

* [x] Does the README explain the purpose and a link to the typed source?
* [x] Do the typings follow the source structure?
* [x] Are they correctly external or ambient modules?

### CODE REVIEW

**Comment by blakeembrey** [comment]
@louy Why not use a promise dependency? Does `mongoose` require a global promise to exist?

**Comment by louy** [comment]
[Mongoose uses](http://mongoosejs.com/docs/promises.html) [`mpromise`](https://www.npmjs.com/package/mpromise). But you can override it by setting `mongoose.Promise` to whatever value you want. 

I'm not sure how to model that in typescript in any way other than using the global promise. Plus `mpromise` isn't typed yet.

**Comment by blakeembrey** [comment]
If it's just a standard `Promise`, just add a dependency on `es6-promise` and use that. Then people can just work, it's what I usually do (since they're all ES6 compliant).

**Comment by louy** [comment]
It's compliant but not standard. They have all those weird methods like `chain/end/fulfil/onFulfil` that no one probably uses.
But what about es6 targets? I know ambient dependencies don't get installed by default but I'm afraid this might change in the future. Will it ever change?

**Comment by blakeembrey** [comment]
Doesn't matter in ES6 targets. That's a global vs a local. No, ambient dependency behaviour will never change.

I'd type it with the `es6-promise` for now. Maybe you can replace it later, but it's better than relying on a global version.

**Comment by louy** [comment]
Makes sense. If anyone wants to use `mpromise` they're free to add typings for it. I've updated the repo.

**Comment by blakeembrey** [comment]
@louy Sorry, I meant use the non-global version that's typed in our registry through NPM. It doesn't introduce globals and let's you use it by doing `import { Promise } from 'es6-promise'`.

**Comment by blakeembrey** [comment]
Here's an example: https://github.com/typed-typings/npm-inquirer/blob/master/lib/inquirer.d.ts#L1. I think we should only rely on globals if the underlying library also does the same - that way, users get accurate compiler errors compared to their runtime.

**Comment by stevehipwell** [comment]
Do we have an estimation as to when this will be added?

**Comment by blakeembrey** [comment]
Once @louy gets back to me.

**Pull request merged**
