### PR TITLE
add glue version

### PR DESCRIPTION
**Pull request by jnath**
**Typings URL:** https://github.com/jnath/typed-glue

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**

add glue.json file with 3.3.0 version in npm folder

### CODE REVIEW

**Comment by blakeembrey** [comment]
Looks reasonable to me. The only change I'd make is here: https://github.com/jnath/typed-glue/blob/master/lib/index.d.ts#L23-L27.

Instead of creating a namespace and exporting it, just export it directly:

```ts
export function compose(manifest: Manifest, options?: Options, callback?: (err?: any, server?: Server) => void);
```

Can you also link to the project? I can't see a link in the README or find it on NPM.

**Comment by jnath** [comment]
ok for me i't done
https://github.com/jnath/typed-glue/pull/1

**Comment by blakeembrey** [comment]
Cheers! Did you want to update the commit hash?

**Comment by jnath** [comment]
sorry,  now yes

**Pull request merged**
