### PR TITLE
fuse.js ES6 Typings

### PR DESCRIPTION
**Pull request by kurtaqui**
**Typings URL: https://github.com/kurtaqui/npm-fuse.js

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**

Add typings from definitely typed which supports ES6 imports.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Typings under NPM should be written in external module format - don't use `declare module "..."` (https://github.com/kurtaqui/npm-fuse.js/blob/master/fuse.js.d.ts#L25-L28).

**Comment by blakeembrey** [comment]
Here's some correct (and improved) typings:

```ts
declare class Fuse {
	constructor (list: any[], options?: Fuse.Options);
	search<T>(pattern: string): T[];
}

declare namespace Fuse {
	export interface Options {
		id?: string;
		caseSensitive?: boolean;
		include?: string[];
		shouldSort?: boolean;
		searchFn?: any;
		sortFn?: (a: { score: number }, b: { score: number }) => number;
		getFn?: (obj: any, path: string) => any;
		keys?: string[] | { name: string; weight: number }[];
		verbose?: boolean;
		tokenize?: boolean;
		location?: number;
		distance?: number;
		threshold?: number;
		maxPatternLength?: number;
	}
}

export = Fuse;
```

**Comment by blakeembrey** [comment]
Thanks, it's looking better. The existing issue is that you've written `github.com:` instead of `github:`.

**Comment by kurtaqui** [comment]
Thanks have missed that, and thanks for the help on the typings :)

**Pull request merged**
