### PR TITLE
the https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/ch…

### PR DESCRIPTION
**Pull request by wujun4code**
**Typings URL:** https://www.npmjs.com/package/chart.js

**Questions (for new typings):**

* [x] Does the README explain the purpose and a link to the typed source?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they correctly external or global modules?

**Change Summary (for existing typings):**

Thanks for contributing! This information helps us and the community stay in sync.

…artjs/chart.d.ts is deprecated.

### CODE REVIEW

**Comment by wujun4code** [comment]
I will fix it.

**Comment by blakeembrey** [comment]
@wujun4code I'm sure you realised the issue, but it's the fact that https://github.com/wujun4code/typed-chart.js/blob/master/index.d.ts has no exports - which makes it a "global" definition. You'll need to refactor it a bit to mirror `chart.js` as an external module.

**Comment by wujun4code** [comment]
@blakeembrey thanks.
I was busy at the weekend.I will recode it to an  external module.

**Comment by wujun4code** [comment]
@blakeembrey done
👌

**Comment by blakeembrey** [comment]
@wujun4code Have you tried this against the original source code? From the docs, it looks like you may need to format the `.d.ts` in `export =` style.

**Comment by wujun4code** [comment]
@blakeembrey Thanks again.
But I do not know how to wrap the Chartjs with `export = ` style.
Should I wrapped it as a `namespace` ? but when wrapped , the code maybe look like this：

```ts
namespacle Chartjs {
  class Chart {
      ....
  }
}
```

is it ok? Thanks.

**Comment by blakeembrey** [comment]
So it'd end up looking like this:

```ts
declare class Chart {
}

declare namespace Chart { ... }

export = Chart;
```

There's a little example in the Typings docs here: https://github.com/typings/typings/blob/master/docs/examples.md#exporting-class--static-methods--utility

**Comment by wujun4code** [comment]
thanks so much.
I will fix it.

**Comment by wujun4code** [comment]
@blakeembrey I recoded it.
Thanks.

**Pull request merged**
