### PR TITLE
npm-through2

### LINKED ISSUE #180: through2

### PR DESCRIPTION
**Pull request by unional**
closes #180

### CODE REVIEW

**Comment by blakeembrey** [comment]
You've got a couple of typos in the definition: `TransfofmCallback` and `FlashCallback`. Also, `push` (https://github.com/typed-typings/npm-through2/blob/master/index.d.ts#L19) does not exist on `through2` - it's a part of `this` in the callback function. I can't recall if you can type `this` in TypeScript yet, but at least it could just be an interface of what `this` should be so you can use it.

**Comment by unional** [comment]
> I can't recall if you can type this in TypeScript yet, but at least it could just be an interface of what this should be so you can use it.

So comment it out for now?

```ts
  // push() is not on through2, it's on `this` in the callback.
  // Don't have a way to type this yet.
  // export function push(data: any): void;
```

**Comment by blakeembrey** [comment]
You can also provide it typed as an interface so people can use it, if needed `export interface This { push() }`.

**Comment by blakeembrey** [comment]
Feel free to merge when you're ready.

**Pull request merged**
