### PR TITLE
Added type definition of headless-gl

### PR DESCRIPTION
**Pull request by LimeStreem**
**Typings URL:https://github.com/jThreeJS/typed-headless-gl** 

**Questions (for new typings):**

* [x] Does the README explain the purpose and a link to the typed source?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they correctly external or global modules?

### CODE REVIEW

**Comment by LimeStreem** [comment]
What is the differences between global module and external module?
This definition works well in my local environment....

How should I fix this?

**Comment by blakeembrey** [comment]
See https://github.com/typings/typings/blob/master/docs/faq.md#types-of-typings.

**Comment by blakeembrey** [comment]
@LimeStreem You have two big bugs. One, it should be in external module format (remove the `declare module '...'` from wrapping everything. The other bug is that `export default` will not work here - it should be `export =`.

**Comment by LimeStreem** [comment]
Thank you a lot!
I would not be able to fix this without your comment.

**Comment by blakeembrey** [comment]
All good. A technique some of us use to when doing `export =`-style typings is to create a namespace and put the interfaces inside. This allows us to access the interfaces outside of the definition correctly. You can see an example here: https://github.com/typings/typings/blob/master/docs/examples.md#function--utility

**Pull request merged**
