### PR TITLE
Create extend.json

### PR DESCRIPTION
**Pull request by unional**
Filling in these fields will make it easier for us to review:

Typings URL: [E.g. http://github.com/typed-typings/npm-extend]
Source URL: [E.g. https://github.com/justmoon/node-extend]

Thanks for contributing!

### CODE REVIEW

**Comment by Fank** [comment]
source url is 404

**Comment by unional** [comment]
Ar, corrected.

**Comment by blakeembrey** [comment]
Did you consider using intersection types instead?

**Comment by unional** [comment]
> Did you consider using intersection types instead?

What do have in mind? Intersecting the two function signatures?

Have yet to see the benefit in this scenario.

**Comment by blakeembrey** [comment]
Whichever you want, I suppose. This would be 100x more useful if TypeScript gets "outer sections" or whatever the latest proposal is.

**Comment by blakeembrey** [comment]
LGTM 👍

**Comment by unional** [comment]
> This would be 100x more useful if TypeScript gets "outer sections" or whatever the latest proposal is.

Which proposal are you referring to? Would like to learn about it.

**Comment by blakeembrey** [comment]
I can't recall a complete proposal, just saw hints around and a real need for it to achieve better type safety. E.g. https://github.com/Microsoft/TypeScript/issues/6895.

**Pull request merged**
