### PR TITLE
Enabled server usage for react-dom

### PR DESCRIPTION
**Pull request by cantide5ga**
**Typings URL:** https://github.com/cantide5ga/typed-react-dom

**Questions (for new typings):**

* [ ] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [ ] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [ ] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**

cantide5ga/typed-react-dom#2

### CODE REVIEW

**Comment by felixfbecker** [comment]
I think you screwed up the rebase 😄

**Comment by cantide5ga** [comment]
Ah dammit what a mess.  Was working off of an old fork that I tried to sync with upstream - perhaps should have just reforked.

Should we cancel this so it doesn't gunk up the history?

**Comment by felixfbecker** [comment]
@cantide5ga I would say just do (assuming typings/registry is tracked under remote `upstream`)
```
git fetch upstream
git reset --hard upstream/master
```
and then re-update the commit hash, commit, and force-push.

**Comment by cantide5ga** [comment]
Thanks for the suggestions, but that's exactly how it got mangled.  I just reforked and opened a new PR.  Amateur hour! https://github.com/typings/registry/pull/727

**Pull request closed without merging**
