### PR TITLE
Added npm simple-xmpp typing

### PR DESCRIPTION
**Pull request by Fank**
https://github.com/Fankserver/npm-simple-xmpp

### CODE REVIEW

**Comment by blakeembrey** [comment]
Awesome :+1: Would be interesting to see this typed with the 1.8 features like string literals for the events (just a thought).

**Comment by Fank** [comment]
I'm not that familiar with typings (currently its more like try and guess :D) could you may provide an example what you mean with "string literals"?

**Comment by blakeembrey** [comment]
@Fank Honestly, it was just an idea and it's a TypeScript feature. I'm just to use it, but I know I can use it for features like this.

References:

* https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#string-literal-types
* https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L4284-L4292

**Comment by Fank** [comment]
:smile: i've searched for something like this. i tried to do it with an "enum" but it didn't worked. This is awesome.
I added it in #122

**Pull request merged**
