### PR TITLE
Update for typings 0.7 and some cleanup

### PR DESCRIPTION
**Pull request by unional**
Improve namings

### CODE REVIEW

**Comment by blakeembrey** [comment]
Looks like a bug in Typings programmatic API, I'll take a look but I'd guess I have some updates to do.

**Comment by unional** [comment]
Could it be because my `npm test` didn't include `typings bundle`? I have it separated.

**Comment by unional** [comment]
`npm run build` = `typings bundle -out test`
`npm test` = ts-node -n test/test.ts`

**Comment by blakeembrey** [comment]
No, it's because the API changed between 0.6 and 0.7 and I just merged 0.7 into master.

**Comment by blakeembrey** [comment]
@unional The last issue is case-sensitivity. Looks like you're using `utils.d.ts` (lower-case), but it's referenced using upper-case (`Utils`).

**Comment by unional** [comment]
Yeah, I updated it locally (on osx). Seems like git push didn't push it up.

**Comment by blakeembrey** [comment]
Renaming case-sensitivity with Git is a PITA, it's ok :+1:

**Comment by blakeembrey** [comment]
Thankfully, you were the only one to use the `.d.ts` paths so no one else needs changing right now :smile: I'll get around to doing properly file resolution when I can.

**Comment by unional** [comment]
I thought that problem only exists on perforce. ....:P

**Comment by unional** [comment]
> Thankfully, you were the only one to use the .d.ts paths so no one else needs changing right now :smile: I'll get around to doing properly file resolution when I can.

Figuring out the best practice along with `jspm`/`systemjs`. :(

**Pull request merged**
