### PR TITLE
Add typings for npm/gulp 3.9.1 and 4.0.0-alpha.2

### PR DESCRIPTION
**Pull request by GiedriusGrabauskas**
**Typings URL:** https://github.com/QuatroTypings/npm-gulp

**Questions (for new typings):**
* [X] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [X] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [X] Are they external or global modules according the source (e.g. see README sources)?

Created new repository with:
* Travis tests.
* Typings tests.
* Different versions.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Would you like access to contribute to the existing typings instead?

**Comment by blakeembrey** [comment]
Also, same as the other PRs, you'll need to stop using this pattern: https://github.com/QuatroTypings/npm-gulp/blob/master/4.0.0-alpha.2/index.d.ts. No one can import anything from your file this way and that file (`contracts`) does not actually exist.

**Comment by DovydasNavickas** [comment]
@blakeembrey, by saying:
>contribute to existing typings

You mean https://github.com/typed-typings/npm-gulp?

**Comment by blakeembrey** [comment]
@DovydasNavickas Yes, those. If either of you want to contribute to them, I can add you to the repositories.

**Comment by DovydasNavickas** [comment]
We'll be glad to help tidy-up the repos as we use quite a few libraries ourselves :clap:
Also, sometimes it's not nice to have to wait for good PRs to be merged, while repo mantainer is on vacation or just doesn't have time to check them :smile:

**Comment by GiedriusGrabauskas** [comment]
:+1:

**Pull request closed without merging**
