### PR TITLE
Added custom elements v1.

### PR DESCRIPTION
**Pull request by turtlemay**
**Typings URL:** https://github.com/turtlemay/typed-custom-elements-v1

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according to the source (e.g. see README sources)?

**Change Summary (for existing typings):**

### CODE REVIEW

**Comment by felixfbecker** [comment]
Generally, versions should be done through branches (preferred) or subfolders

**Comment by turtlemay** [comment]
It's a browser spec so there is no semver and only one version, strictly speaking.

**Comment by felixfbecker** [comment]
Define the methods as methods instead of arrow function properties

**Comment by felixfbecker** [comment]
Otherwise LGTM

**Comment by turtlemay** [comment]
Done.

**Pull request merged**
