### PR TITLE
Would you verify is everything correct, please. My apology if something is not in proper order - I'm new in TypeScript and JavaScript.

### PR DESCRIPTION
**Pull request by pr0peller**
Typings URL: [https://github.com/pr0peller/jquery-pagings-typings]

**Questions (for new typings):**
* [X] Does the README explain the purpose and a link to the typed source?
* [X] Do the typings follow the source structure?
* [X] Are they correctly external or ambient modules?

### CODE REVIEW

**Comment by blakeembrey** [comment]
Unfortunately things in `npm/` should be in external module format - if you want to write a global module you can put it in `global/`. Aside from that, you can also kill the module declaration to correct it (https://github.com/pr0peller/jquery-pagings-typings/blob/dev/index.d.ts#L76-L78).

**Comment by pr0peller** [comment]
Hi,

I have removed the module and variable declarations. I red about modules but steel I'm not sure that i understand the concept of global and external module. Would you verify please.

**Comment by pr0peller** [comment]
If I understood correct, module declaration must be removed and all interfaces have to be exported.

**Comment by blakeembrey** [comment]
Hey! Sorry I didn't get back to you earlier, do you happen to be using the jQuery typings from DefinitelyTyped?

**Comment by pr0peller** [comment]
Hi, I use jQuery from typings not from DefinitelyTyped.

**Comment by blakeembrey** [comment]
Oh, sorry, I believe they still come from DefinitelyTyped then 😄 

```
jquery                        dt     http://jquery.com/                                                    1        2016-04-17T21:32:36.000Z
```

So, with that in mind, have you tested this definition? I believe it'll cause some problems because it relies on interface merging with the global jQuery interface. Sorry to mess you around, it's just that's the difference between `--ambient` and without. Unless we get a working external module version of jQuery, you might want to use a global version of this module and put it in `global/` instead.

**Comment by pr0peller** [comment]
I actually think about this, and I thing that it is better to put in global/. I think that is the best. Wold you please verify just the index.d.ts file?

**Comment by blakeembrey** [comment]
@pr0peller How do you import it? Do you need to create a module so `import 'jquery-paging'` works?

**Comment by pr0peller** [comment]
I was using that as in the first (original) commit with the "declare module" and just `/// <reference path="..."` in the beginning of the file.

**Comment by blakeembrey** [comment]
Right, but `declare module 'x'` wouldn't work with normal definitions - global definitions aren't wrapped up though, so if you're relying on the import working you'll need it again. Sorry for the confusion.

**Comment by pr0peller** [comment]
What I did is I looked from ambient definition for "jstree" (installed from typings) and i did this the same way. It was working for me and decided to share it with other people. I'm new to typescript and JavaScript (I'm coming from C#) and those module things are very confusing for me. For a week now, as you can see, I'm struggling to figure out what is the way to export module in description so other people can access it and use it. If I follow you, what you were saying i have to export the interfaces which I want to be accessible. Em I right sir?

**Comment by blakeembrey** [comment]
Yes.

**Comment by blakeembrey** [comment]
But only if it's a non-ambient definition. The difference is that `--ambient` installs verbatim, while without it wraps it up for TypeScript to understand. Since you want to write an ambient (or global) definition, you just need to declare the interfaces. The reason I asked if you import it using `import ''` or if it exists globally already is because of how you'd use it. It's a bit of a mess, but if you need `import 'foo'` to work you need a `declare module 'foo' {}` to exist.

**Comment by blakeembrey** [comment]
Feel free to share a direct use-case of how you're using the library in JavaScript and we can figure out how to make it work in TypeScript too (especially if nothing I'm saying makes sense, it's not your fault).

**Comment by pr0peller** [comment]
I think the problem is that this is jQuery plugin and it extends jQuery by adding `.paging` function to it.
I have declare all the interfaces. This should work for as ambient definition. I'll take a look again, when my knowledge and understanding abort those things is better and stronger. Thanks for the explanation. Deeply appreciated you patient. Thank you.  :)

**Comment by blakeembrey** [comment]
No worries. You can always do test installations locally to check if it works, might be easier to test that way too 😄 (if you're not already).

The current implementation _will_ work (I believe), but you won't be able to do `import 'x'` (because there's no module declaration). As long as you aren't doing that, then it's fine. There **a lot** of different ways to load JavaScript because there's been no standard for a long time - E.g. `<script />` tags (which I guess you're doing now), ES6 imports (`import 'x'`) which TypeScript transpiles to other implementations (because no one supports it fully yet), CommonJS (synchronous `require('x')`), AMD (asynchronous `define(['x'], function (x) {})`), and other custom implementations.

**Comment by pr0peller** [comment]
Thank you. I'm trying to use RequireJS because it make sense for me. and it works good with TypeScript. Steel a lot to learn though. Thank you one more time :)

**Comment by blakeembrey** [comment]
Personally I'd recommend just sticking with CommonJS - there's a much bigger ecosystem and less issues to worry about. With AMD, you can only use AMD or UMD modules - which is a very small ecosystem and blocks out most of the NPM ecosystem. That's just my advice though 😄 I know it can be a pain to get your head around all the ways you can do things in JavaScript.

**Pull request merged**
