### PR TITLE
Add `normalizr@2.x` typings

### PR DESCRIPTION
**Pull request by unindented**
Typings URL: https://github.com/unindented/typed-normalizr
Source URL: https://github.com/gaearon/normalizr

### CODE REVIEW

**Comment by blakeembrey** [comment]
@unindented Are you a maintainer of `normalizr`? Would you be interested in keeping the type definitions inside the repo itself instead? Doing that would provide immediate value for TypeScript users instead of making them use Typings.

**Comment by unindented** [comment]
@blakeembrey You are right, that's the better option. Adding a `typings` field to the `package.json` that points to the `.d.ts` file would be enough, right?

**Comment by blakeembrey** [comment]
Yes, that's all you need to do and TypeScript users will appreciate it :smile:

**Comment by blakeembrey** [comment]
You're welcome to ping me too, if you need a definition review.

**Comment by unindented** [comment]
@blakeembrey I've created a PR, if you have the time to review: https://github.com/gaearon/normalizr/pull/84

**Pull request closed without merging**
