### PR TITLE
Add typings for stash-rest-api v2.6.0

### PR DESCRIPTION
**Pull request by zergmk2**
**Typings URL:** <https://github.com/zergmk2/typed-stash-rest-api>

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**
`None`

Signed-off-by: Lu_Cao <zergmk2@gmail.com>

### CODE REVIEW

**Comment by blakeembrey** [comment]
The only comment I have is on https://github.com/zergmk2/typed-stash-rest-api/blob/master/src/index.d.ts#L2. Could you use a version that's provided externally so people don't need to install an extra thing to use these?

**Comment by felixfbecker** [comment]
https://github.com/zergmk2/typed-stash-rest-api/blob/master/src/index.d.ts#L1
I don't think we should have triple slash references like these in typings

https://github.com/zergmk2/typed-stash-rest-api/blob/master/src/index.d.ts#L2
This is semantically incorrect, `import * as x from 'y'` means x is a plain object of all exports from module y, not a constructor.

https://github.com/zergmk2/typed-stash-rest-api/blob/master/src/index.d.ts#L7
Instead of defining a namespace, just export all the members directly - otherwise you won't get IntelliSense when doing a selective import.

**Comment by zergmk2** [comment]
@blakeembrey 
I've added the dependency of promise definition in typings.json.
https://github.com/zergmk2/typed-stash-rest-api/blob/master/typings.json#L8

**Comment by felixfbecker** [comment]
@zergmk2 You should use one from the registry ;)

**Comment by zergmk2** [comment]
@felixfbecker 
Thanks for your review comments, below are my responses:
>1) https://github.com/zergmk2/typed-stash-rest-api/blob/master/src/index.d.ts#L1
I don't think we should have triple slash references like these in typings.

I've updated the code and removed the triple slash references.
>2)https://github.com/zergmk2/typed-stash-rest-api/blob/master/src/index.d.ts#L2
This is semantically incorrect, import * as x from 'y' means x is a plain object of all exports from module y, not a constructor.

I don't call the Promise's constructor, I just use an exported interface in this module.

>3)https://github.com/zergmk2/typed-stash-rest-api/blob/master/src/index.d.ts#L7
Instead of defining a namespace, just export all the members directly - otherwise you won't get IntelliSense when doing a selective import.

I've explicitly exported all the class and functions in the namespcae.

**Comment by zergmk2** [comment]
@felixfbecker 
oh, I got it. I will update my code. Thank you.

**Comment by felixfbecker** [comment]
> I've explicitly exported all the class and functions in the namespcae.

You should just remove the `namespace` completely

**Pull request closed without merging**
