### PR TITLE
Added retext definitions

### PR DESCRIPTION
**Pull request by joewashear007**
* Added the definitions file for retext and its dependencies

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks for the ping, looks like wonderful work. Unfortunately I don't know anything about these typing and I'm not using them, making me not very good at potentially maintaining them!

**Comment by blakeembrey** [comment]
No worries :smile: If the public API changes, feel free to ping me or @joewashear007 and we can keep the TypeScript type definitions in sync.

**Comment by wooorm** [comment]
:+1: I’ll try my best!

**Pull request merged**
