### PR TITLE
typings for karma-fixture

### PR DESCRIPTION
**Pull request by evictor**
**Typings URL:** https://github.com/evictor/typings-karma-fixture

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [ ] Are they external or global modules according the source (e.g. see README sources)?

### CODE REVIEW

**Comment by felixfbecker** [comment]
https://github.com/evictor/typings-karma-fixture/issues/1

**Comment by felixfbecker** [comment]
If this is a global typing, it should go to the `global` folder, not `npm`

**Comment by evictor** [comment]
Roger that, I have moved it to global/ folder.

**Comment by evictor** [comment]
Also made some changes on source typings to conform to standard of using namespace instead of module for global typings.

**Pull request merged**
