### PR TITLE
Added jointjs typings

### PR DESCRIPTION
**Pull request by CaselIT**
Filling in these fields will make it easier for us to review:

Typings URL: [E.g. https://github.com/CaselIT/typings-jointjs]
Source URL: [E.g.  https://github.com/clientIO/joint]

Thanks for contributing!

### CODE REVIEW

**Comment by unional** [comment]
Seems like it is exposing:
> JointJS library exports three global variables: `joint`, `V` and `g`.

Would it be better to put `dia` `ui` `shapes` `util` and `layout` under `joint`?
Those will be place at the global namespace right now.

**Comment by CaselIT** [comment]
No it exposes also the objects `dia` `ui` `shapes` `util` and `layout`

**Comment by unional** [comment]
Oh, interesting. Never know it works that way. Thanks.

**Comment by unional** [comment]
It's ES6 -> CommonJS interop

**Comment by CaselIT** [comment]
I'm not sure I follow. Do you mean the missing exports in the namespace declaration?

**Comment by unional** [comment]
Nope. I tested it and it is working.
`jointjs` is using `export =` syntax at `index.js`, and what you have is in `ES6 syntax`. So it is a ES6 -> CommonJS interop.

**Comment by unional** [comment]
Not sure if that is a good idea to do so, as it might backfire as the CommonJS -> ES6 interop issue.
I think there are some ES6->CommonJS interop trick `babel` is doing.
But I guess this would be fine.

@blakeembrey , what do you think?

**Comment by unional** [comment]
@CaselIT you probably aware of it, but for reference, what I'm talking about is related to:
https://github.com/Microsoft/TypeScript/issues/7398

**Comment by CaselIT** [comment]
I was not aware of it, thanks for pointing it out. I think I did experience something similar while writing the type definition for this library. If load this library with system.js as global the external module as it is written is incorrect, while it works when loading it as commonjs. 
Still I think most people will use the ambient definitions and load the library with a script tag.
Do you have any advice to avoid the issue?

**Comment by unional** [comment]
> Still I think most people will use the ambient definitions and load the library with a script tag

Loading from script tag just means the typings needs to be ambient/global/script. So the `/global/*` should take care of it.



> Do you have any advice to avoid the issue?

Currently no, unfortunately. That why I think the issue is massive.  The best we can do is to stay as close to the shape of the source as possible.

i.e. in this case keep it in the `export =` syntax.

**Comment by CaselIT** [comment]
I tried to change the type definition, did you mean like they are now? They effectively are as before.

https://github.com/CaselIT/typings-jointjs/blob/test-export/index.d.ts

**Comment by unional** [comment]
yup. :+1:

**Comment by CaselIT** [comment]
I've updated the pull request.

**Comment by unional** [comment]
FYI Having some difficulty to merge

**Comment by CaselIT** [comment]
Can I help?

**Comment by unional** [comment]
It's related to the repo setting I think. So need @blakeembrey's help on it.

**Comment by CaselIT** [comment]
I can re-fork the repo and risubmit the pull request if you think that it would help.

**Comment by unional** [comment]
Thanks. But it's not just your PR. Same for all other PRs. :smirk:

**Comment by CaselIT** [comment]
:+1:

**Comment by blakeembrey** [comment]
Sorry, it appeared to be an odd restriction that comes with the enablement of the squash option. It should now be fixed for collaborators.

**Pull request merged**
