### PR TITLE
Create http-assert.json

### PR DESCRIPTION
**Pull request by jkeylu**
**Typings URL:** https://github.com/jstype/typed-npm-http-assert

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

### CODE REVIEW

**Comment by felixfbecker** [comment]
Can I ask you what the organization jstype is about? https://github.com/jstype

**Comment by jkeylu** [comment]
It's my hobby project of typescript

2016-08-31 7:07 GMT+08:00 Felix Becker <notifications@github.com>:

**Comment by blakeembrey** [comment]
@jkeylu Would you like to help with @types?

**Comment by jkeylu** [comment]
Yes, I will be happy to do that.

2016-08-31 13:29 GMT+08:00 Blake Embrey <notifications@github.com>:

**Pull request merged**
