### PR TITLE
add global lodash

### PR DESCRIPTION
**Pull request by unional**
Filling in these fields will make it easier for us to review:

Typings URL: [E.g. http://github.com/typed-typings/npm-lodash]
Source URL: [E.g. https://github.com/lodash/lodash]

Thanks for contributing!

### CODE REVIEW

**Comment by blakeembrey** [comment]
@unional Is there something stopping us from doing the `declare global` trick here?

**Comment by unional** [comment]
Do you think the `declare global` trick will work if it is being referenced multiple times?

I recall it will lead to `duplicate identifier` error. But need to validate.

**Comment by louy** [comment]
IMO, a global module should never be referenced multiple times. I don't like the idea of having a typing file for a global var that the user will have to expose manually anyway. 

moreover, module authors should never expose anything globally. think about having a module that uses lodash while another uses underscore.

**Comment by unional** [comment]
These are for supporting user using the module through script tag

**Comment by unional** [comment]
Merge since the augmentation trick is not working.

**Pull request merged**
