### PR TITLE
Add typings for npm/gulp 3.9.1 and 4.0.0-alpha.2

### PR DESCRIPTION
**Pull request by GiedriusGrabauskas**
**Typings URL:** https://github.com/typed-typings/npm-gulp

Old pull request: #520

### CODE REVIEW

**Comment by blakeembrey** [comment]
If possible, we need to fix these dependencies ASAP: https://github.com/typed-typings/npm-gulp/blob/master/4.0.0-alpha.2/typings.json#L6-L15. It's not useful to have things in the registry broken.

**Comment by blakeembrey** [comment]
If you also get a chance, please fix the exports: https://github.com/typed-typings/npm-gulp/blob/master/4.0.0-alpha.2/index.d.ts#L206. Currently nothing other than that export can be accessed, making the namespace redundant.

**Comment by DovydasNavickas** [comment]
Isn't it that identical name namespace `GulpClient` and declared var `GulpClient` kind of "extend" each other? In code completion when importing gulp as:
```
import * as gulp from 'gulp';
```
and writing:
```
gulp.
```
we can see both things: interfaces from the namespace and the functions from interface `Gulp`:

image

**Comment by blakeembrey** [comment]
Yes, you're right. It's a very non-idiomatic way to do it. This whole thing should just be top-level exports without any need for a namespace, let alone this namespace interface trick.

**Comment by blakeembrey** [comment]
For example, it could just be:

```ts
export function src(...): ...;
```

**Pull request merged**
