### PR TITLE
Add gulp-util.json

### PR DESCRIPTION
**Pull request by demurgos**
**Typings URL:** https://github.com/demurgos/typed-gulp-util

**Questions (for new typings):**
- [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
- [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
- [x] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**

### CODE REVIEW

**Comment by demurgos** [comment]
I just read about the [namespace hack](https://github.com/typings/discussions/issues/32). I am using it internally: should I update my definitions ?

**Comment by demurgos** [comment]
Well, I checked some other typings and it looks like they are also using `import * as ...` internally, so I'd like to know if my definitions are valid or not.

**Comment by felixfbecker** [comment]
No, they are semantically incorrect by ES6 spec. It's a hack. For modules that use `export =`, use `import x = require('')`

**Comment by felixfbecker** [comment]
LGTM. One minor note: https://github.com/demurgos/typed-gulp-util/blob/master/index.d.ts#L17
What is the reason to export this as a type? You can easily use `typeof colors` to get the type, but you are breaking the naming convention of uppercase names for types here. Also applies a few lines further down again.

**Comment by demurgos** [comment]
This is a remaining from when I was trying to re-export namespaces. Since there is no `export namespace File = Vinyl`, this was the closest I could get so I just tried it - but since it does not work I used a normal namespace for `File` and forgot to remove it for the others.

I just fixed it at the moment.

**Comment by felixfbecker** [comment]
Oh btw you can also just do `export {colors, date}`

**Comment by demurgos** [comment]
Closing as gulp-util is deprecated

**Pull request closed without merging**
