### PR TITLE
add npm/react-select

### PR DESCRIPTION
**Pull request by zaytsevvla**
https://github.com/zaytsevvla/typed-react-select

**Questions (for new typings):**

* [x] Does the README explain the purpose and a link to the typed source?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [ ] Are they correctly external or global modules?

**Change Summary (for existing typings):**

Thanks for contributing! This information helps us and the community stay in sync.

### CODE REVIEW

**Comment by zaytsevvla** [comment]
` Attempted to compile "react" as an external module, but it looks like a global module`
please give me an example of using global module

**Comment by unional** [comment]
Your dependency is wrong. The dt~react should be a global.

I saw a PR on react coming in. Do you want to use that instead?

**Comment by blakeembrey** [comment]
@zaytsevvla https://github.com/typings/typings/blob/master/docs/external-modules.md and https://github.com/typings/typings/blob/master/docs/faq.md#types-of-typings.

**Comment by zaytsevvla** [comment]
`I saw a PR on react coming in. Do you want to use that instead?` - nope
but please, let me know when it would be merged, i'll fix this typing.

**Comment by blakeembrey** [comment]
@zaytsevvla Can you change https://github.com/zaytsevvla/typed-react-select/blob/master/lib/Select.d.ts#L1 to `import from 'react'` instead? `dt~react` isn't actually a module, it's `react` "from" `dt` (DefinitelyTyped).

**Comment by blakeembrey** [comment]
Also, is https://github.com/zaytsevvla/typed-react-select/blob/master/typings.json#L10 working for you somehow? That shouldn't actually work currently, I'd recommend making it a `globalDependency` or maybe even a `peerDependency`.

**Comment by zaytsevvla** [comment]
@blakeembrey used `peerDependency` as in package and `import from 'react'`. look like it works
But i can't understand why `dependencies` + `import from 'react'` didn't work.

**Comment by blakeembrey** [comment]
@zaytsevvla Because the `react` definitions you are using are written in "global" module format, not as external modules. Typings does not use the global sub-dependencies, they are used for client hints.

**Comment by blakeembrey** [comment]
By the way, it's `peerDependencies`, but I'm happy to merge as is and you can correct it later when needed 😄

**Pull request merged**
