### PR TITLE
IScroll ts definitions.

### PR DESCRIPTION
**Pull request by StefanKoenen**
**Typings for iscroll;**
Typings URL: https://github.com/StefanKoenen/npm-iscroll
Source URL: https://github.com/cubiq/iscroll

**Typings for siwtchery;**
Typings URL: https://github.com/StefanKoenen/npm-switchery
Source URL: https://github.com/abpetkov/switchery

### CODE REVIEW

**Comment by blakeembrey** [comment]
Should https://github.com/StefanKoenen/npm-switchery/blob/master/index.d.ts#L51 be a class instead of an interface? Also, there's nothing exported from either https://github.com/StefanKoenen/npm-switchery/blob/master/index.d.ts or https://github.com/StefanKoenen/npm-iscroll/blob/master/index.d.ts - they should have some parts exported so you can import them.

**Comment by StefanKoenen** [comment]
Thanks for your feedback, I've updated the typings.

**Comment by blakeembrey** [comment]
You will need to update the hashes in the registry.

**Comment by StefanKoenen** [comment]
Hmm i tried to update the iscroll hash, but the npm test sais it's unable to resolve;

```
TypingsError: Unable to resolve "github:StefanKoenen/npm-iscroll#4a9e9131925192117623be010728d3113000aede"
    at resolveError (D:\git\registry\node_modules\typings-core\dist\lib\dependencies.js:345:12)
    at D:\git\registry\node_modules\typings-core\dist\lib\dependencies.js:317:31
    at process._tickCallback (node.js:412:9)
npm ERR! Test failed.  See above for more details.
```

**Comment by blakeembrey** [comment]
image

**Comment by StefanKoenen** [comment]
how did you get this response? :D

**Comment by blakeembrey** [comment]
Sorry, the was by running the CLI tool. `typings install github:StefanKoenen/npm-iscroll#4a9e9131925192117623be010728d3113000aede`. The information is there in the error too, I'm just not printing it which I need to also fix.

**Comment by unional** [comment]
@StefanKoenen , sorry, last night I saw an issue with `IScroll` and added to the registry without realizing you already have a repo for it.

I looked at your code. The `IScroll` library is exporting in commonjs fashion so `export class IScroll` does not work because it is named export in ES6.

I like you separate the interfaces thou. I have incorporate your ideas to [`typed-iscroll`](https://github.com/typed-typings/typed-iscroll). I'm adding you as an contributor. would that work for you?

**Comment by StefanKoenen** [comment]
@unional that would be nice, thnx.

**Comment by unional** [comment]
Cool.  Can you update this PR to include just the switchery?

**Comment by StefanKoenen** [comment]
@unional I'll close this PR and start a new one for switchery :).
Did you add me as contributor?

**Comment by unional** [comment]
Yes I did

**Pull request closed without merging**
