### PR TITLE
Delete es6-promise.json

### PR DESCRIPTION
**Pull request by unional**
now integrated to source.

### CODE REVIEW

**Comment by felixfbecker** [comment]
What about targets like Node 5 that have promises but cannot use es6 lib.d.ts?

**Comment by unional** [comment]
this is for `es6-promise`. It is integrated to the source repo. Will be release very soon. Already merged
https://github.com/stefanpenner/es6-promise/pull/211

**Comment by felixfbecker** [comment]
Ah, okay. But then we should at least wait until the release is out.

**Comment by unional** [comment]
Yes, thus `waiting for response` tag.

**Comment by blakeembrey** [comment]
I'm still a little concerned about people using this definition that isn't particularly the `es6-promise` module. I'm guilty of using it like this 😄 Perhaps we should move this to `common/`?

**Pull request merged**
