### PR TITLE
Create we-app.json

### PR DESCRIPTION
**Pull request by Emeryao**
**Typings URL:** [https://github.com/Emeryao/typed-we-app](https://github.com/Emeryao/typed-we-app)

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

### CODE REVIEW

**Comment by felixfbecker** [comment]
Is there no english documentation?

**Comment by Emeryao** [comment]
@felixfbecker 
No, there is no documentation in English, cause WeChat is a mobile app mainly used in Mainland China.
Sorry about that

**Comment by felixfbecker** [comment]
Okay. Cannot really review then. I will trust you that this is a global definition and not a module

**Comment by Emeryao** [comment]
@felixfbecker 
Thank you for trusting me.
It is a global definition. 😆

**Pull request merged**
