### PR TITLE
Remove outdated Electron typings

### PR DESCRIPTION
**Pull request by miniak**
Electron is working on providing an official electron.d.ts (automatically generated from the API docs) electron/electron#4875. Please raise any concerns / ideas there.

### CODE REVIEW

**Comment by felixfbecker** [comment]
@blakeembrey will this break consumers?

**Comment by miniak** [comment]
@felixfbecker I hope nobody is these typings as they are horribly outdated.

**Comment by unional** [comment]
Will not break consumer as it is per commit. 
Just that user can't install a new copy.

**Comment by miniak** [comment]
I would be great if you could clarify the advantages / disadvantages of this repo over DefinitelyTyped. Is there any reason to keep using this place now that npm supports installing typings?

**Comment by miniak** [comment]
Also, the current situation is confusing for users, as they get this error:
```
typings install electron

typings ERR! message Unable to find "electron" ("npm") in the registry.
typings ERR! message However, we found "electron" for 2 other sources: "dt" and "env"
typings ERR! message You can install these using the "source" option.
...
```

**Comment by unional** [comment]
> Also, the current situation is confusing for users, as they get this error:

This, for `typings` user, should not be confusing. That just means you need to do `typings install env~electron` or `typings install dt~electron` (which, in the case, should be the same as `npm install @types/electron`

**Comment by blakeembrey** [comment]
I merged this for now. Feel free to ping me in the deletion thread or just delete the @types repo whenever. Everyone using the current current versions in the registry will continue working, just no one will be able to find these typings going forward. It will break if we delete the repo itself, though, so we can probably just deprecate it for some time first.

**Pull request merged**
