### PR TITLE
Add declaration for bignumber.js

### PR DESCRIPTION
**Pull request by felixfbecker**
**Typings URL:** https://github.com/felixfbecker/typed-bignumber.js

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project? _yes_
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)? _yes_
* [x] Are they external or global modules according the source (e.g. see README sources)? _external_

### CODE REVIEW

**Comment by blakeembrey** [comment]
That's some amazing documentation!

The only thing I'd note is that you _may_ want to put the interfaces into a `BigNumber` namespace. This would allow people to still access those interfaces outside the type definition, which can be important sometimes. E.g.

```ts
const config: BigNumber.Configuation = { ... }
```

**Comment by felixfbecker** [comment]
@blakeembrey Thanks :)
I opened https://github.com/MikeMcl/bignumber.js/issues/97 to hopefully be able to remote `export =` completely, which would allow to export the interfaces. I think namespace / interface merging only works with interfaces, not classes - don't really want to declare a global namespace.

**Comment by blakeembrey** [comment]
No, it does work. It's not global either.

```ts
declare class BigNumber {}
declare namespace BigNumber {}

export = BigNumber;
```

**Comment by blakeembrey** [comment]
Here's an example of it working to a different project I contributed to: https://github.com/kevinbeaty/any-promise/blob/master/index.d.ts.

**Comment by felixfbecker** [comment]
@blakeembrey So then I have to reference every interface like this, right?
```ts
declare namespace BigNumber {
  export interface Configuration {}
}
declare class BigNumber {
  config(config: BigNumber.Configuration): BigNumber.Configuration;
}
```
I would like to avoid that :/

**Comment by blakeembrey** [comment]
It's nicer than not allowing anyone to access the interfaces.

**Comment by unional** [comment]
I should update the example to reflect this. :)

**Comment by felixfbecker** [comment]
I will remove `export = ` instead thanks to https://github.com/MikeMcl/bignumber.js/commit/34b79d1a0cbca866469cf75abdc62aecd40dd35d :)

**Pull request merged**
