### PR TITLE
Update npm/request

### PR DESCRIPTION
**Pull request by Demurgos**
**Typings URL:** https://github.com/louy/typed-request

**Change Summary:**

- Update project to use standard structure
- Rely on [tough cookie's definitions](https://github.com/typed-typings/npm-tough-cookie) for `Cookie` and `CookieJar`

### CODE REVIEW

**Comment by Demurgos** [comment]
The above `typings` may cause some issues with the `jar` property of `CoreOptions` (too strictly typed).

There is a pending fix: until https://github.com/louy/typed-request/pull/4
It's best to wait until it's merged and the hash for registry is updated before merging this branch.

(If I close this Github PR (`Close and comment` button), will I be able to reopen it once it's fixed or will I need to create a new PR ?)

**Comment by Demurgos** [comment]
The typings are ready now.

Change:
 - Type `CoreOptions.jar` as `boolean | CookieJar`
 - Correctly expose the sync wrapper for `CookieJar`

**Comment by blakeembrey** [comment]
Did you want to get the updated cookie jar merged into `request` first?

**Comment by Demurgos** [comment]
Due to the wrapper, the CookieJar interface is no longer directly exposed.
It is not necessary to update it for this PR.
(I'll work again on `request` tomorrow so I'll update it by the way)

`request` exposes the following typings from `tough-cookie`:
`Cookie`, `CookieStore`, `SetCookieOptions`

**Pull request merged**
