### PR TITLE
Added rwlock typings

### PR DESCRIPTION
**Pull request by CaselIT**
Filling in these fields will make it easier for us to review:

Typings URL: [E.g. https://github.com/CaselIT/typings-rwlock]
Source URL: [E.g. https://github.com/71104/rwlock]

Thanks for contributing!

### CODE REVIEW

**Comment by unional** [comment]
https://github.com/71104/rwlock/blob/master/package.json#L18
Seems like the main is `lock`, may be better to name your typings as `lock.d.ts`

**Comment by unional** [comment]
Pure styling: since it is namespaced in `ReatWriteLock` already, you probably don't need to name the interfaces as `RW*` https://github.com/CaselIT/typings-rwlock/blob/master/rwlock.d.ts#L13

**Comment by CaselIT** [comment]
Even if the import is with `rwlock`?
Regarding the `RW` I'll remove them.

**Comment by unional** [comment]
> Even if the import is with rwlock

The general convention would be following what's in the `package.json/main` for "require-ability" in case there are multiple files. Doesn't really matter in this case. :smile:

@blakeembrey, I asked about this a while ago:

This case is clear:
```
// in source:
// package.json/main = "a.js" or "a"
// folder:
a.js
lib/b.js

// in typings:
// typings.json/main = "a.d.ts"
```

Would like to confirm on this:
```
// in source:
// package.json/main = "lib/a.js" or "lib/a"
// folder:
lib/a.js
lib/b.js

// in typings:
// typings.json/main = "a.d.ts" or "lib/a.d.ts"?
```

**Comment by CaselIT** [comment]
I'll also rename the file then :+1: 
Should I also put it under `lib`?

**Comment by unional** [comment]
I think you don't have to. You can change that in the future if needed. Will not do any harm since it is the main.

**Comment by CaselIT** [comment]
Committed the changes :+1:

**Comment by blakeembrey** [comment]
FWIW, you won't be able to access `ReadWriteGeneric` outside of the module. Hope that's ok.

@unional Let's stay true to the source. If anything, that's the source of truth and there needs to be no extra questions.

**Comment by CaselIT** [comment]
`ReadWriteGeneric` is only used to avoid code repetition so there is no need to access it outside the module. That's why I defined it outside the namespace.

**Comment by unional** [comment]
> @unional Let's stay true to the source.

So meaning keep it as lib/a.d.ts. :smile:

**Pull request merged**
