### PR TITLE
Added filename.js typings

### PR DESCRIPTION
**Pull request by faceleg**
Filling in these fields will make it easier for us to review:

Typings URL: https://github.com/66pix/filename.js-typings
Source URL: https://github.com/66pix/filename.js

Thanks for your time!

### CODE REVIEW

**Comment by Fank** [comment]
Is it possible to place the typings in the source repository instead of a new one?

**Comment by faceleg** [comment]
Yes of course, I wasn't sure if that was preferred (we could note this in the readme?)

**Comment by faceleg** [comment]
Would I put the `node.d.ts` and `browser.d.ts` files at the root of the filename.js repo or in a typings folder?

**Comment by Fank** [comment]
@blakeembrey or @unional can help

**Comment by faceleg** [comment]
OK thanks. I'll wait for instructions before mangling anything else.

**Comment by unional** [comment]
You and put is as `index.d.ts` and point to it through `package.json/typings`

For the content, you should not wrap them inside `declare module` just export them at top level

Seems like your nose and browser version are identical in api (briefly looked at it through phone). So you don't need two versions either. 

Hope it helps!

**Comment by unional** [comment]
Using `export =` syntax as in your code

**Comment by unional** [comment]
http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

**Comment by unional** [comment]
You can also configure this for your browser consumption:
https://github.com/blakeembrey/popsicle/blob/master/package.json#L12-L18

**Comment by faceleg** [comment]
That's helpful, thanks. Just started with TS last night, appreciate the tips.

**Comment by faceleg** [comment]
Done - I see github has a "squash commits" option when merging now, let me know if you want me to squash manually anyway.

**Comment by unional** [comment]
As you have added it to the package itself, you don't need this PR. tsc will get the typings automatically.

**Comment by faceleg** [comment]
Hooray I'm learning!

**Pull request closed without merging**
