### PR TITLE
add vsts-task-lib typing

### PR DESCRIPTION
**Pull request by bryanmacfarlane**
**Typings URL:** https://github.com/Microsoft/typed-vsts-task-lib

**Questions (for new typings):**

* [X] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [X] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [X] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**

Initial typing.  The typing is generated as part of the build from: https://github.com/Microsoft/vsts-task-lib

The lib has been in production for Visual Studio Team System build tasks for awhile.  But I'm new to typings (started today), so forgive rookie mistakes.

### CODE REVIEW

**Comment by unional** [comment]
Is there any reason you don't want to add the typings directly in  https://github.com/Microsoft/vsts-task-lib?

**Comment by unional** [comment]
It currently fails because it is a global script, not external module. You need to unwrap the `declare module 'abc'` and use `declare namespace ...` or export them at top level.

**Comment by bryanmacfarlane** [comment]
@unional - I could do that.  I read we were supposed to create a repo called typed-[name]

The issue I'm having right now, is it works locally (incuding tests)

```bash
$ git clone https://github.com/Microsoft/typed-vsts-task-lib test-task-lib
$ cd test-task-lib/
$ npm install

> typed-vsts-task-lib@0.8.4 postinstall /Users/bryan/Projects/test-task-lib
> typings install && cd test && typings install --global


├── node (global)
└── q (global)


├── node (global)
├── q (global)
└── vsts-task-lib (global)

$ npm test

> typed-vsts-task-lib@0.8.4 test /Users/bryan/Projects/test-task-lib
> tsc -p test

$ echo $?
0
```

But when run by travis in PR, it fails:

https://travis-ci.org/typings/registry/builds/144305036

**Comment by unional** [comment]
That's because in your test code you are treating it as global, thus it works.
https://github.com/Microsoft/typed-vsts-task-lib/blob/master/test/typings.json#L8

However, it should really be an external module, not global, as you use it through `import tl = require('vsts-task-lib/task');`

**Comment by unional** [comment]
https://github.com/typings/typings/blob/master/docs/external-modules.md
https://github.com/typings/typings/blob/master/docs/faq.md#types-of-typings

**Comment by bryanmacfarlane** [comment]
@unional - thanks for help so far.

My build uses dts-generator as part of the build and produces _build/.d.ts/vsts-task-lib.d.ts.  It's unclear to me how to export at the top level. 

Consumers of the lib already do import tl = require('vsts-task-lib/task'); so I want to retain that as well.

Thanks again.

**Comment by bryanmacfarlane** [comment]
I think the dts-generator was causing my issues - trying to use the separate files outputted by tsc declaration true and going that route

**Comment by bryanmacfarlane** [comment]
Yes, that was it.  For generation I was using something to bundle after my build (dts-generator but there's dts-bundle).  I changed to having compiler do it (tsc --declaration true) which generated multiple files and I used those instead.

**Comment by blakeembrey** [comment]
@bryanmacfarlane If you're the module author, it would be easier to maintain the definition in your own repo instead. There's some guidance in the README (https://github.com/typings/registry#as-package-author) but let me know if there's anything else we can help with.

**Comment by bryanmacfarlane** [comment]
Makes sense.

After reading through the links my take away is since I release on npm, ship the js and .d.ts files with the npm package and point to the .d.ts entry with typings property of package.json.  then, in the typings registry, I point to npm:{nameInNpmRegistry}

I'll make those changes.  Please ack if that sounds right.

**Comment by blakeembrey** [comment]
@bryanmacfarlane Correct, but you don't need to update the Typings registry at all then. It'll just work, then you can avoid the registry altogether.

**Comment by bryanmacfarlane** [comment]
Ahh.  Awesome

**Comment by bryanmacfarlane** [comment]
Hopefully last question ...

I do above with typings entry in package.json and publish
From the link it seems like typescript will resolve types by looking in node_modules and everything works for consumers that just install my package.  

But, they need to also pull typings for types from dependencies I expose (q, node).  If I published in my own typed-xxx repo the typings.json would declare the dependences

So do users do `typings install npm~vsts-task-lib` to get it to pull down node and q typings?

Does that mean I should have a typings.json in the package in addition to the package.json property?

**Comment by blakeembrey** [comment]
> But, they need to also pull typings for types from dependencies I expose (q, node). If I published in my own typed-xxx repo the typings.json would declare the dependences

Correct, yes. But you can also do that from your published module on NPM also. However, global sub-dependencies are never installed by Typings (only printed that the users needs to install them).

> So do users do typings install npm~vsts-task-lib to get it to pull down node and q typings?

Yes.

> Does that mean I should have a typings.json in the package in addition to the package.json property?

You can. That's what I do currently, for example in https://github.com/blakeembrey/popsicle. Then someone needs to install it separately using `typings install npm:popsicle`. It's not ideal, but the process is going to be getting better with TypeScript 2.0.

**Comment by unional** [comment]
Yes, you should keep the `typings.json` in there.
Use would need to do `typings install -save npm:vsts-task-lib` to install the typings locally (from `node_modules/...`. notice it is `:`, not `~`).

However, in your case it will not really install `q` and `node` because both of them are global.
`typings install` will print out message saying so and user need to manually install them.

There is no other way for `node`. For `q`, if the typings were in module format (published under `typings/registry/npm/q.json`), then `typings install` will bundle and install it automatically.

**Comment by bryanmacfarlane** [comment]
Thanks everyone.  I got it all working.

Typescript (and especially new async await) is a game changer for node.  Keep up the good work.

Closing this PR since I'm distributed with my npm package.

**Pull request closed without merging**
