### PR TITLE
add definition for mailgen

### PR DESCRIPTION
**Pull request by vothanhkiet**
**Typings URL:** https://github.com/vothanhkiet/mailgen-typings
**Source URL:** https://github.com/eladnava/mailgen
**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?  - Yes
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)? - Yes
* [x] Are they external or global modules according the source (e.g. see README sources)? - External

### CODE REVIEW

**Comment by blakeembrey** [comment]
Sorry for the delay. Looking at the module compared to your typings, it looks like there's a bug. If you look at https://github.com/eladnava/mailgen#usage, the usage is `export =` style and not `export Mailgen`. Can you refactor to make sure it follows the correct export styles?

**Comment by vothanhkiet** [comment]
You're right. I've just refactor, remove all export and only use 

> export = Mailgen 

However, when I use in my code, tsc throw error ```TS2497: Module ''mailgen'' resolves to a non-module entity and cannot be imported using this construct.```. The compile code still work, I received the email . After add 

> namespace Mailgen {
> }

I don't get error anymore. Can you explain this ? I'm still new at TypeScript

P/S: I will make new pull request again.

**Comment by blakeembrey** [comment]
You don't need to make a new PR, just update this one.

The way to import a CommonJS module is `import x = require('x')`. Using `import * as x from 'x'` is a fallback for ES6-modules, but TypeScript also made the decision to support namespaces for that style also since all modules pre-1.5 were written like that (1.5 was the introduction of ES6 support). You can read more here: https://www.typescriptlang.org/docs/handbook/modules.html.

**Comment by blakeembrey** [comment]
You might want to move the interfaces (https://github.com/vothanhkiet/mailgen-typings/blob/master/index.d.ts#L4-L35) into the namespace so you can access them externally to the module.

**Comment by vothanhkiet** [comment]
Thanks for pointing that out, can you recheck again please ?

**Comment by blakeembrey** [comment]
Never seen that approach (https://github.com/vothanhkiet/mailgen-typings/blob/master/index.d.ts#L1-L2). If it works, it works 😄

**Pull request merged**
