### PR TITLE
Add typings for gulp-sourcemaps v1.6.0 and v2.0.0-alpha

### PR DESCRIPTION
**Pull request by natevecc**
**Typings URL:** https://github.com/natevecc/typed-gulp-sourcemaps

**Questions (for new typings):**

* [ ] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [ ] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [ ] Are they external or global modules according the source (e.g. see README sources)?

I followed the [gulp typings](https://github.com/typings/gulp-typings) structure to handle the multiple versions. If that's not right let me know and I can fix. Also if you want to move this under the typings organization I'm happy to assist with that as well.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Looks good! Very welcome addition. But you don't have to declare a namespace and export it, you can export the types directly using `export interface Whatever` etc.

**Comment by natevecc** [comment]
@felixfbecker I updated the typings repo with your change. If it looks good to you I'll update this PR with the new commit hash.

**Comment by natevecc** [comment]
@felixfbecker actually after rereading your comment not sure exactly what you wanted me to do.

- export just the namespace
- export everything individually
- export only the functions

sorry new to typescript and want to get this right 😄

**Comment by felixfbecker** [comment]
It's good as-is, just also export the interfaces aswell.

**Comment by natevecc** [comment]
@felixfbecker ok done and updated this pr with the new commit hash.

**Comment by felixfbecker** [comment]
LGTM

**Comment by unional** [comment]
Thanks!

**Pull request merged**
