### PR TITLE
Create jweixin.json

### PR DESCRIPTION
**Pull request by Emeryao**
**Typings URL:** [https://github.com/Emeryao/typed-jweixin](https://github.com/Emeryao/typed-jweixin)

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according to the source (e.g. see README sources)?

PS: WeChat (Chinese name Weixin) is a mobile social app mainly used in Mainland China, so the documentation is in Chinese.

### CODE REVIEW

**Comment by unional** [comment]
I'm suspecting this and the `we-app` should be under `env` instead of `global`.

How to you get access to the library when you write code? Through script tag?

**Comment by Emeryao** [comment]
@unional 
For this one, yes, the jweixin library should be referenced in a script tag. 
But for `we-app` it is accessible globally just like the `chrome` variable when developing a chrome extension

**Comment by unional** [comment]
In that case this should remain in `global` and `we-app` should be in `env`

**Comment by Emeryao** [comment]
@unional 
Thanks for your correction. 👍 
I'll fix that and make another PR 😆

**Pull request merged**
