### PR TITLE
Add types for darrylwest/mock-browser

### PR DESCRIPTION
**Pull request by nohira**
**Typings URL:** https://github.com/nohira/typed-mock-browser

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

How can I determine the last point?

### CODE REVIEW

**Comment by felixfbecker** [comment]
These typings are global and should go under global/ and have a global: true flag set

**Comment by nohira** [comment]
I've moved to global.
Can you just explain how you determine if it's global or not?

**Comment by blakeembrey** [comment]
@nohira the criteria is "does it have an `import` or `export` at the top-level". This is TypeScript's semantics, when it does it makes the definition a module and when it does not it makes it a global definition. More nuance, we try to write certain modules in either global or external module format depending on the consumption - it wouldn't make sense to write a global version of an NPM module, for instance. Does this help? 😄

**Comment by nohira** [comment]
@blakeembrey Yeah, I guess
Do you mean it's more in the syntax and the usage?
That I can write more like in the [nock types](https://github.com/nohira/npm-nock/blob/master/index.d.ts)?

**Comment by blakeembrey** [comment]
@nohira Correct, yeah. You'd want to write it in external module format and have an export at the top level (removing https://github.com/nohira/typed-mock-browser/blob/master/index.d.ts#L3-L5). Otherwise, it's considered "global" and people might not connect it to that NPM module.

**Comment by nohira** [comment]
@blakeembrey I've changed to non global format. I hope I did understand well.
Please tell me if something is wrong.

**Comment by blakeembrey** [comment]
Looks good 👍

**Pull request merged**
