### PR TITLE
Add typings for stripe

### PR DESCRIPTION
**Pull request by taxpon**
**Typings URL:** https://github.com/taxpon/typings-stripe

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

### CODE REVIEW

**Comment by blakeembrey** [comment]
Not sure if I'm missing something, but the first example uses `require('stripe')('token')` - these typings won't be able to handle that?

**Comment by amooz** [comment]
@taxpon any progress answering @blakeembrey's questions?  I was about to create new definitions for stripe but found your waiting pull request first.

**Comment by taxpon** [comment]
@blakeembrey @amooz Sorry for late response. I just created type definition which is correspond to [this in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/stripe/stripe.d.ts). I updated some interfaces. 

@blakeembrey 
> Not sure if I'm missing something, but the first example uses require('stripe')('token') - these typings won't be able to handle that?

This is another definition, maybe [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7171d1588156a7c5702f11a37bd4490e86f08665/stripe-node/stripe-node.d.ts). So not included in this PR.

**Comment by blakeembrey** [comment]
@taxpon Can you link the docs/library this is for then? In the README it says it's https://stripe.com/docs/api, and those are the ones I looked at.

**Comment by taxpon** [comment]
@blakeembrey Sorry for unclear document. I fixed README in [typings-stripe](https://github.com/taxpon/typings-stripe) repository. Please check it.

**Comment by blakeembrey** [comment]
@taxpon I'm still confused what these typings are for though. Can you share the project that this types?

@amooz Were you after the node.js typings?

**Comment by taxpon** [comment]
@blakeembrey I can not share you my private repo, but this typing helps developers to build [payment form with stripe.js](https://stripe.com/docs/custom-form).

**Comment by blakeembrey** [comment]
@taxpon Thanks. I don't need your private repo, that's ok 😄 I just want to figure out what the definitions are actually for. That link helps - so it's the `stripe.js` library. Is it the `v2` implementation too? If it's only a global, you shouldn't need to declare a module called `Stripe` to use it (https://github.com/taxpon/typings-stripe/blob/master/stripe.d.ts#L116-L119).

Can you link to those `stripe.js` docs? It's helpful (https://stripe.com/docs/custom-form).

**Comment by taxpon** [comment]
@blakeembrey I think this typings support v2 and I updated [README](https://github.com/taxpon/typings-stripe), so it would be great if you review it :)

**Comment by blakeembrey** [comment]
@taxpon Looks good. Would you like to update this PR? You've got a small typo on the readme (thier -> their) and https://github.com/taxpon/typings-stripe/blob/master/typings.json#L4 should be `"global": true` (for 1.0).

**Comment by taxpon** [comment]
@blakeembrey Oops.. I fixed it. Please review.

**Comment by blakeembrey** [comment]
Thanks @taxpon!

**Pull request merged**
