### PR TITLE
add tree-kill

### PR DESCRIPTION
**Pull request by oherman1**
**Typings URL:** https://github.com/oherman1/typed-node-tree-kill

**Questions (for new typings):**

* [x]  Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**

### CODE REVIEW

**Comment by unional** [comment]
I guess you can just do:

```ts
declare function kill(processId: number, signal?: string, callback?: (err: any) => any): void;

export = kill;
```

**Comment by unional** [comment]
https://github.com/oherman1/typed-node-tree-kill/blob/master/typings.json#L4
should point to the source homepage.
Also it would be great if you include a link to the source repo.

**Comment by unional** [comment]
Or in the repo description. example: https://github.com/typed-typings/npm-node-noop

**Comment by oherman1** [comment]
Thanks for the guidance, doing my first attempt in publishing typings.

**Comment by blakeembrey** [comment]
@oherman1 In your README, you can link to the original source: https://github.com/pkrumins/node-tree-kill. That way people can read the README and jump to the full documentation. Also, I'd probably refactor the module to look like https://github.com/typings/registry/pull/521#issuecomment-224697942 when you get a chance 😄

**Pull request merged**
