### PR TITLE
added types

### PR DESCRIPTION
**Pull request by zelein**
**Typings URL:** [typed-selenium-standalone](https://github.com/zelein/typed-selenium-standalone)

**Questions (for new typings):**

* [ ] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [ ] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [ ] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**

added types for [selenium-standalone](https://github.com/vvo/selenium-standalone)

### CODE REVIEW

**Comment by felixfbecker** [comment]
Your GitHub email is broken

**Comment by zelein** [comment]
@felixfbecker broken in what way?

**Comment by blakeembrey** [comment]
@zelein Mostly just your work email used in git is not associated with your GitHub account, which is resulting in the un-styled commits you have.

**Comment by zelein** [comment]
Oh, I see. I was wondering why those commits were showing up without my profile. Thanks.

**Pull request merged**
