### PR TITLE
Add knockout-postbox@0.5.2

### PR DESCRIPTION
**Pull request by jgoz**
Typings URL: https://github.com/jgoz/typed-knockout-postbox
Source URL: https://github.com/rniemeyer/knockout-postbox

### CODE REVIEW

**Comment by unional** [comment]
HI, you should do module augmentation to add extensions to knockout

**Comment by unional** [comment]
The global one is good. Exception you can you `describe namespace` instead of `declare module`

**Comment by jgoz** [comment]
@unional I'm doing that in the external typings [here](https://github.com/jgoz/typed-knockout-postbox/blob/master/index.d.ts#L10). Did you have something else in mind?

**Comment by jgoz** [comment]
> The global one is good. Exception you can you describe namespace instead of declare module

https://github.com/jgoz/typed-knockout-postbox/commit/982661db75cd28ffbb1b3e86a9593f82adab5c5b

**Comment by unional** [comment]
OH you are right. :+1:

**Comment by unional** [comment]
LGTM. Will merge when I can access computer

**Comment by jgoz** [comment]
Want me to use the new commit hash for the `module` -> `namespace` change?

**Comment by unional** [comment]
Oh, yes. Can you update it?

**Comment by jgoz** [comment]
@unional #300.

**Pull request merged**
