### PR TITLE
update riot.json

### PR DESCRIPTION
**Pull request by effervescentia**
**Typings URL:** https://github.com/effervescentia/typed-riot

**Change Summary:**

- fix `mixin` declarations
- add global `mixin` declaration
- update `root` type to be custom extension of `HTMLElement` instead of `Node`

### CODE REVIEW

**Comment by unional** [comment]
You need to reorder the overloads. The first one will always win.

**Comment by unional** [comment]
https://github.com/unional/typescript-guidelines/blob/master/pages/typings/overloading.md

**Comment by blakeembrey** [comment]
@unional Although correct, in this case because all the arguments are required (none optional) it should always resolve to the correct one (based on arity). I agree keeping it in mind is important though, and making the order more clear can help (and help you not forget this fact).

**Comment by unional** [comment]
Oh, you are correct. 👍

**Pull request merged**
