### PR TITLE
Added a link to the expect definition file

### PR DESCRIPTION
**Pull request by andrew-w-ross**

### CODE REVIEW

**Comment by blakeembrey** [comment]
Awesome :+1: You're just missing one thing, and that's to specify `main` in `typings.json`. That's what the build is complaining about and I'll definitely improve that error ASAP.

**Comment by blakeembrey** [comment]
Oh, I just realised. Is this meant to be an ambient module? I suspect you want to make it external (https://github.com/andrew-w-ross/typings-expect/blob/master/expect.d.ts) by pulling everything that's inside the ambient declaration outside and removing it.

**Comment by andrew-w-ross** [comment]
Oh it's not supposed to be an ambient module. What have I done wrong?

**Comment by blakeembrey** [comment]
Looks like you managed to fix it up :+1: Cheers!

**Pull request merged**
