### PR TITLE
Updated gravatar

### PR DESCRIPTION
**Pull request by Fank**
Removed obsolete namespace

### CODE REVIEW

**Comment by blakeembrey** [comment]
Awesome, cheers!

**Comment by Fank** [comment]
@blakeembrey is it possible to be an collaborator?

**Comment by blakeembrey** [comment]
@Fank Of the registry? I think so, see https://github.com/typings/registry/issues/70. I'll add you now, just make sure every PR is still reviewed, and no pushing directly to master (I would enable that protection, but then it blocks people from merging PRs that are even slightly out of date with `master`).

**Comment by Fank** [comment]
Yea. I'm maintainer of multiple repo's i know how to handle it :D

**Comment by blakeembrey** [comment]
Awesome, the registry is (hopefully) mostly helping people out and getting them started contributing. You're welcome to traverse the issues, of course. If you feel like there should be a guide or doc for this (because that's what I'm thinking now), just let me know - I tend to work faster when I know someone wants a feature.

**Pull request merged**
