### PR TITLE
typings for prompt

### PR DESCRIPTION
**Pull request by sinse**
**Typings URL:** https://github.com/sinse/npm-prompt

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**

### CODE REVIEW

**Comment by felixfbecker** [comment]
Please remove the `declare module`

**Comment by sinse** [comment]
"declare module" removed

**Comment by felixfbecker** [comment]
Please depend on the node typings from the registry, not DT

**Comment by sinse** [comment]
fixed

**Comment by sinse** [comment]
hmm sry to ask this question:
did i need to put a new pull request in order to update the npm/prompt.json to reference the last commit ?

**Comment by felixfbecker** [comment]
You said fixed so I assumed you updated the PR. Now you need a new one, yes.

**Comment by sinse** [comment]
new pull request #759 to fix the depend on the last commit

**Comment by sinse** [comment]
sorry

**Pull request merged**
