### PR TITLE
Add bluebird

### PR DESCRIPTION
**Pull request by unional**

### CODE REVIEW

**Comment by blakeembrey** [comment]
Nice :+1: 

P.S. One thing to keep in mind is `.gitignore` for typings compiled output (https://github.com/unional/typed-bluebird). I saw a lot of TODOs too, but for `Promise.all` here's a tweak that can be done: https://github.com/typings/typed-es6-promise/blob/master/dist/es6-promise.d.ts#L48 (stolen from TypeScript core).

**Comment by unional** [comment]
I'm just moving what's in definitely typed over and make it compatible. Will definitely improve on it as they go.

> .gitignore for typings compiled output

What do you mean?

**Comment by blakeembrey** [comment]
This directory: https://github.com/unional/typed-bluebird/tree/master/typings

**Comment by unional** [comment]
Oh yeah. Missed it. Will update the generator!

**Pull request merged**
