### PR TITLE
Add nightmare.json

### PR DESCRIPTION
**Pull request by JumpeiArashi**
**Typings URL:** https://github.com/JumpeiArashi/typed-nightmare
**Source URL:** https://github.com/segmentio/nightmare/

**Questions (for new typings):**

* [x] Does the README explain the purpose and a link to the typed source?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they correctly external or global modules?

**Change Summary (for existing typings):**

nightmare.d.ts doesn't exist in typings.

* create nightmare.d.ts for version 2.x (with electron version)
* updated typings to 1.0.x on generated by `typings-generator`
* pass travis ci test

See https://github.com/JumpeiArashi/typed-nightmare/blob/master/index.d.ts for detail. Thanks!

Thanks for contributing! This information helps us and the community stay in sync.

### CODE REVIEW

**Comment by blakeembrey** [comment]
@JumpeiArashi Looks great. You may want to put all those extra interfaces into the `Nightmare` namespaces so people can still access them outside your typings.

Side note: What exactly is the `electron` namespace?

**Comment by JumpeiArashi** [comment]
Are _all those extra interfaces_ `NightmareOptions`, `Paths` and `Switches` ? Would it be better to expose those Interface?

> What exactly is the electron namespace?

Nightmare is wrapped electron. So some Object (mainly Interface as nightmare arguments) are electron's. So I defined electron namespace to separate into Nightmare original interface for readability. Would it be better to re-define as Nightmare interface ,too?

**Comment by blakeembrey** [comment]
Yeah, it just let's people re-use those interfaces. Sometimes really helpful - especially when you want to use that types to work with on your own objects. Thanks 😄

**Comment by JumpeiArashi** [comment]
Thank you for merging:metal: Surely, I understood benefits of exporting interfaces. Thanks.

**Pull request merged**
