### PR TITLE
Add npm:domready

### PR DESCRIPTION
**Pull request by unional**
https://github.com/typings/typings/issues/129

### CODE REVIEW

**Comment by blakeembrey** [comment]
Awesome, cheers! The failure is complaining about the usage of `browser` field without `main` set. The browser field is an override, you'll still need `main`. In this case, I'd just change `"browser"` to `"main"` and update this PR and we'll be passing :+1:

Reference: https://github.com/unional/typed-domready/blob/master/typings.json

Thanks for this! You're helping identify places where my document must be terrible too.

**Comment by unional** [comment]
Thanks for the feedback. It passes now. :+1:

**Comment by unional** [comment]
I rebase it to your latest code to get rid of the extra merge

**Comment by blakeembrey** [comment]
LGTM :+1: Thanks for contributing.

**Pull request merged**
