### PR TITLE
Update node.json

### PR DESCRIPTION
**Pull request by blakeembrey**
**Typings URL:** https://github.com/types/env-node

**Change Summary (for existing typings):**

Tidied up a couple of types: https://github.com/types/env-node/commits/master.

### CODE REVIEW

**Comment by zelein** [comment]
This merge has broken all of my projects that are using the env-node typings. It has specifically broken references to the "express-serve-static-core" project as well as the "types-is" project.

**Comment by blakeembrey** [comment]
@zelein Are these projects from DefinitelyTyped? I removed the deprecated methods because of exactly this reason, they kept being used and shouldn't be. Express has correct definitions under `npm`, and I can type `type-is` today if that is helpful.

**Comment by zelein** [comment]
Typing out the type-is would be very helpful if you can spare the time for
it. We have an internal declaration file, but it is basic and out of date.

The more I'm using TS the more I'm seeing the typings declarations to be
much more up to date than their DT counterparts.

**Comment by blakeembrey** [comment]
@zelein Sorry for the delay, it took me days to finish the RethinkDB typings (it's insane!). I quickly typed out `type-is`, you can see the definition here: https://github.com/types/npm-type-is. It's a pretty small one 😄

**Comment by zelein** [comment]
Thank you @blakeembrey. Much appreciated!

**Pull request merged**
