### PR TITLE
Add `servicestack-client` to registry.

### PR DESCRIPTION
**Pull request by Layoric**
**Typings URL:** https://github.com/ServiceStack/servicestack-client/blob/master/typings.json

**Questions (for new typings):**
* [X] Does the README explain the purpose of the typings and have a link to the JavaScript project?

GitHub repository for NPM module with JS. Native TypeScript library, wanting to share d.ts files via both to allow flexibility of use. 
* [X] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?

Yes, in ./lib folder
* [X] Are they external or global modules according the source (e.g. see README sources)?

External as it is available on NPM.

Let me know if any other info is required :+1:

### CODE REVIEW

**Comment by unional** [comment]
As the error suggest, you need to write it in external module format.
You can see some examples here:
https://github.com/typings/typings/blob/master/docs/examples.md
Remove the `declare module '...' {`.

**Comment by Layoric** [comment]
@unional Thanks for the info. 

I think I might have misunderstood the different "sources". 

Given this is a http client library and (to me at least) makes the most sense to import and use it as such:
`import {JsonServiceClient} from 'servicestack-client';`
Might this make more sense as a global source rather than removing the `declare module`?

Thanks again.

**Comment by unional** [comment]
It should be kept as external module format. It's a module, not a global script.

You don't need to use `declare module 'servicestack-client' {` to tell it is named `servicestack-client`. It is defined in the registry (`npm/servicestack-client.json`) and can be changed by the consumer.

See if this would make sense to you: https://github.com/typings/typings/blob/master/docs/external-modules.md

**Comment by unional** [comment]
👍

**Pull request merged**
