### PR TITLE
Jacada Interact Extension

### PR DESCRIPTION
**Pull request by doronguttman**
**Typings URL:** https://github.com/jacadainc/typed-interact-extension

**Questions (for new typings):**

* [ ] Does the README explain the purpose of the typings and have a link to the JavaScript project?
The README explains the purpose, but the JavaScript is proprietary and not available to link to.
 
* [ ] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
There is specifically associated js file.

* [ ] Are they external or global modules according the source (e.g. see README sources)?
yes

**Change Summary (for existing typings):**

### CODE REVIEW

**Comment by blakeembrey** [comment]
@doronguttman Thanks for the contribution. I don't know a lot about how you distribute the definition, but if it's proprietary and you're the author would it make more sense to provide the definition/instructions with the library itself?

**Comment by doronguttman** [comment]
You may be right, though, the library is a 3rd-party, which we have no control over, but would like to provide users a simple method to install typings when they develop extensions.

**Comment by blakeembrey** [comment]
Ok, I've merged it now 👍

**Comment by doronguttman** [comment]
Thanks!

**Comment by doronguttman** [comment]
@blakeembrey I just made an update to the typings repo and the hash I used in the PR is no longer valid.
This brings out a question. Is there a way not to define a specific hash on the typings so you always get the latest commit?

**Comment by unional** [comment]
It is not advised to do that because that means whenever you make a commit you can potentially break all of your consumers.
Think about someone running travis and suddenly it starts failing without any code change.

**Comment by doronguttman** [comment]
I see your point, but how is that different from me updating the repo, then doing a PR to update the typings repo?

**Comment by unional** [comment]
Because the user won't get any intermittent commits. When a PR is filed here, we can help taking a look to make sure the typings is in good shape.

**Comment by unional** [comment]
Also, user won't automatically gets the updated typings unless they do `typings install <pkg>`
`typings install` would download and use the same old commit.

**Pull request merged**
