### PR TITLE
in 'npm/react-router' add typing for withRouter function (2.4.0)

### PR DESCRIPTION
**Pull request by zaytsevvla**
**Typings URL:** https://github.com/zaytsevvla/typings-react-router

### CODE REVIEW

**Comment by blakeembrey** [comment]
That's unfortunate, it looks like @andrew-w-ross is inactive. Would you interested in helping maintaining a fork in @typed-typings instead?

**Comment by zaytsevvla** [comment]
@blakeembrey it would be nice to move my repos to typed-typings i think.
about maintaining: i just write typings on things that i touch in my work.

**Comment by blakeembrey** [comment]
@zaytsevvla No worries, as do I 😄 (well, that includes open source). I can add you to @typed-typings and you can fork into there, if you'd like, then update this PR?

**Comment by zaytsevvla** [comment]
done

**Comment by blakeembrey** [comment]
Awesome, cheers! It looks like there's a lot more issues we'll want to port across when we get a chance.

**Comment by andrew-w-ross** [comment]
@blakeembrey Hey sorry not inactive just crazy busy with work on backend stuff.

**Comment by blakeembrey** [comment]
@andrew-w-ross No worries, good to hear! If you get a chance, I sent you an invite to @typed-typings - you're welcome to move your repos across and we can help share/maintain the load.

**Comment by andrew-w-ross** [comment]
@blakeembrey Will do.

**Pull request merged**
