### PR TITLE
add d.ts for https://www.npmjs.com/package/leancloud-storage.

### PR DESCRIPTION
**Pull request by wujun4code**
**Typings URL:**https://www.npmjs.com/package/leancloud-storage

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

**Change Summary (for existing typings):**

Define file hosted in:https://github.com/leancloud/typed-leancloud-storage

### CODE REVIEW

**Comment by unional** [comment]
Seems like you are part of `leancloud` already. Is there any reason of not putting the typings directly in the source repo?

**Comment by wujun4code** [comment]
@unional , the js project is another project group.em,I will make a pr to it.

**Comment by unional** [comment]
That would be the best. `tsc` will pick it up automatically and user need no extra action.

Add the file path to `package.json/typings`

**Comment by wujun4code** [comment]
```
Add the file path to package.json/typings
```
sorry. I do not understand add which file path to package.json? or typings.json?

Thanks.

**Comment by unional** [comment]
The `typings` property in `package.json`:

https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

**Comment by wujun4code** [comment]
yes.I will. but could you merge this pr first?
I am using it for some projects.so I want to use `typings install leancloud-storage` to manage the lib.
NPM package.json like this [momentjs/package.json](https://github.com/moment/moment/blob/develop/package.json). I know how to append. When next time js group push it to NPM.I will put the d.ts in it.

Thanks again.
💯

**Comment by unional** [comment]
Sure. :)

**Pull request merged**
