### PR TITLE
added iron-tree, iron-beam and ironworks typings

### PR DESCRIPTION
**Pull request by ironman9967**
**Typings URL:** 

**Questions (for new typings):**

* [x] Does the README explain the purpose and a link to the typed source?
* [x] Do the typings follow the source structure?
* [x] Are they correctly external or ambient modules?

**Change Summary (for existing typings):**

Thanks for contributing! This information helps us and the community stay in sync.

### CODE REVIEW

**Comment by blakeembrey** [comment]
@ironman9967 If you're the package author, you don't need to add it to the registry here. Just add `typings` to `package.json`, and TypeScript will pick it up 😄

**Comment by ironman9967** [comment]
Oh, great. Thanks!

On Thu, May 5, 2016, 7:35 PM Blake Embrey <notifications@github.com> wrote:

> @ironman9967 <https://github.com/ironman9967> If you're the package
> author, you don't need to add it to the registry here. Just add typings
> to package.json, and TypeScript will pick it up 😄
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/typings/registry/pull/394#issuecomment-217310085>
>
-- 
Tyson Hester
865.272.9174
TysonDHester@gmail.com

**Comment by blakeembrey** [comment]
Closing the PR for now. Please feel free to ask any questions, if you need a hand adding type definitions.

**Comment by ironman9967** [comment]
I have a (hopefully quick) question about defining types for a library I'm
building called ironworks.

I have a dependent library (hapi) with a class I need to extend. Before I
started working with Typings, I had a *import hapi = require('hapi')*
statement in my ironworks d file and I'm extending the class with *export
class MyServer extends hapi.Server { ... } *

This works fine in ironworks, but when I go to install it's typings into
another app using *typings install npm:ironworks* I get:
- typings ERR! message Unable to read typings for "hapi". The author of
"ironworks" needs to check the entry paths in "package.json" are up to date

Hapi is installed as an ambient dependency in ironworks.

Any ideas? I really appreciate the help and keep up the good work with
typings!

On Sat, May 7, 2016 at 1:27 AM Blake Embrey <notifications@github.com>
wrote:

> Closing the PR for now. Please feel free to ask any questions, if you need
> a hand adding type definitions.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/typings/registry/pull/394#issuecomment-217609120>
>
-- 
Tyson Hester
865.272.9174
TysonDHester@gmail.com

**Comment by blakeembrey** [comment]
Unfortunately it expects the definition to be in dependency format and not ambient. It's been asked a few times, and it's like that because otherwise the user would need to install `hapi` themselves and it _may_ be incompatible. However, there's been some discussion around relaxing this restriction because it confuses people. Any thoughts on the topic? Of course, it'll work if `hapi` becomes a regular dependency with existing versions.

**Pull request closed without merging**
