### PR TITLE
Adding typings for pify

### PR DESCRIPTION
**Pull request by cyounkins**
**Typings URL:** https://github.com/cyounkins/typed-pify

**Questions (for new typings):**

* [X] Does the README explain the purpose and a link to the typed source?
* [X] Do the typings follow the source structure?
* [X] Are they correctly external or ambient modules?

### CODE REVIEW

**Comment by blakeembrey** [comment]
FWIW, it is possible to achieve more complex implementations using generics: https://github.com/typed-typings/npm-thenify/blob/master/index.d.ts.

Thanks! 👍

**Comment by blakeembrey** [comment]
Do you want to at least make the return a function that returns a promise, instead of `any`?

**Comment by cyounkins** [comment]
I would love to make the types better, but I messed with it for a long while and couldn't get it to work.

pify(function) = promise but pify(module) = module, but the types don't match because the methods of said module are all mutated. I looked at Bluebird.promisifyAll but it wasn't any better.

In the typings I have commented out definitions for zero and one-arg functions, but I couldn't get them to work in conjunction with module definitions. Perhaps you could try?

**Comment by blakeembrey** [comment]
Promifying a single function is easy to provide type signatures for (see link above). A whole module is unfortunately impossible, because there's no way in TypeScript to iterate over keys of an object to define a new type. I'm happy to merge as is, in that case.

**Pull request merged**
