### PR TITLE
Create koa.json

### PR DESCRIPTION
**Pull request by jkeylu**
**Typings URL:** https://github.com/types/npm-koa

**Questions (for new typings):**

* [x] Does the README explain the purpose of the typings and have a link to the JavaScript project?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they external or global modules according the source (e.g. see README sources)?

### CODE REVIEW

**Comment by felixfbecker** [comment]
Is it possible to use classes? Or will the class/namespace merging not work?
https://github.com/koajs/koa/blob/v2.x/lib/application.js#L32

**Comment by felixfbecker** [comment]
https://github.com/types/npm-koa/blob/master/lib/application.d.ts#L65-L67
I think exporting type aliases to the interfaces would be better suited here

**Comment by jkeylu** [comment]
You're right

2016-09-03 16:42 GMT+08:00 Felix Becker <notifications@github.com>:

**Comment by felixfbecker** [comment]
LGTM

**Pull request merged**
