### PR TITLE
Moved repositories to typed-typings

### PR DESCRIPTION
**Pull request by Fank**
I only moved them

+ Updated
Typings URL: https://github.com/typed-typings/npm-generate-help
Source URL: https://github.com/vdemedes/generate-help

### CODE REVIEW

**Comment by unional** [comment]
I thought you will be using `<author>-<repo>`? :stuck_out_tongue_winking_eye: 

LGTM

**Comment by Fank** [comment]
Can't rename the repos

**Comment by unional** [comment]
Oh yeah. @blakeembrey that is an issue with Github.
I am knockout of owner status on `generator-typings` also. :stuck_out_tongue_winking_eye:

**Pull request merged**
