### PR TITLE
Add npm/are-we-there-yet

### PR DESCRIPTION
**Pull request by Demurgos**
Typings URL: https://github.com/Demurgos/typed-are-we-there-yet
Source URL: https://github.com/iarna/are-we-there-yet

A few notes about these typings:
 - I don't have a clue about how to expose events

 - The definitions use node's `stream` while the real module uses `readable-stream`. Both should be compatible but it has to be fixed once the definitions for `readable-stream` are available.

- I had an issue with the presence of one method (`finish()` on `TrackerStream`). I opened a ticket on their repo because I think there might be a difference between what is documented and what is implemented.

### CODE REVIEW

**Comment by blakeembrey** [comment]
What do you mean by exposing events? Have you checked out TypeScript string literals?

**Comment by Demurgos** [comment]
The different objects extend `EventEmitter`. I heard about TypesScript string literals and use them in my normal projects. I already had the idea to use them to define the expect event/listener pairs. The problem is that it is somehow incompatible with EventEmitter:

node's `EventEmitter`:
````typescript
declare module "events" {
    export class EventEmitter implements NodeJS.EventEmitter {
        static listenerCount(emitter: EventEmitter, event: string): number;

        addListener(event: string, listener: Function): EventEmitter;
        on(event: string, listener: Function): EventEmitter;
        once(event: string, listener: Function): EventEmitter;
        removeListener(event: string, listener: Function): EventEmitter;
        removeAllListeners(event?: string): EventEmitter;
        setMaxListeners(n: number): void;
        listeners(event: string): Function[];
        emit(event: string, ...args: any[]): boolean;
   }
}
````

TrackerGroup with literals (I stripped comments)
````typescript
class TrackerBase extends EventEmitter { ... }

export class TrackerGroup extends TrackerBase {
  constructor(name?: string);
  addUnit<T extends Tracker>(otherTracker: T, weight?: number): T;
  addUnit<T extends TrackerGroup>(otherTracker: T, weight?: number): T;
  addUnit<T extends TrackerStream>(otherTracker: T, weight?: number): T;
  newGroup(name?: string, weight?: number): TrackerGroup;
  newItem(name?: string, todo?: number, weight?: number): Tracker;
  newStream(name?: string, todo?: number, weight?: number): TrackerStream;
  debug(): string;

  // override with literals:
  addListener(event: "change", listener: (name?: string, completed?: number, tracker?: TrackerGroup) => any): this;
  on(event: "change", listener: (name?: string, completed?: number, tracker?: TrackerGroup) => any): this;
  once(event: "change", listener: (name?: string, completed?: number, tracker?: TrackerGroup) => any): this;
  removeListener(event: "change", listener: (name?: string, completed?: number, tracker?: TrackerGroup) => any): this;
  removeAllListeners(event?: "change"): this;
  setMaxListeners(n: number): void;
  listeners(event: "change"): Array<(name?: string, completed?: number, tracker?: TrackerGroup) => any>;
}
````
This leads to:
````error
TSError: ⨯ Unable to compile TypeScript
..\out\main.d.ts (52,14): Class 'TrackerGroup' incorrectly extends base class 'TrackerBase'.
  Types of property 'addListener' are incompatible.
    Type '(event: "change", listener: (name?: string, completed?: number, tracker?: TrackerGroup) => any) =...' is not assignable to type '(event: string, listener: Function) => this'.
      Type '(event: "change", listener: (name?: string, completed?: number, tracker?: TrackerGroup) => any) =...' provides no match for the signature '(event: string, listener: Function): this' (2415)
..\out\main.d.ts (127,3): Specialized overload signature is not assignable to any non-specialized signature. (2382)
..\out\main.d.ts (128,3): Specialized overload signature is not assignable to any non-specialized signature. (2382)
..\out\main.d.ts (129,3): Specialized overload signature is not assignable to any non-specialized signature. (2382)
..\out\main.d.ts (130,3): Specialized overload signature is not assignable to any non-specialized signature. (2382)
..\out\main.d.ts (131,3): Specialized overload signature is not assignable to any non-specialized signature. (2382)
..\out\main.d.ts (133,3): Specialized overload signature is not assignable to any non-specialized signature. (2382)
    at getOutput (D:\projects\typed\typed-are-we-there-yet\node_modules\ts-node\src\ts-node.ts:210:13)
    at Object.loader (D:\projects\typed\typed-are-we-there-yet\node_modules\ts-node\src\ts-node.ts:225:23)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at D:\projects\typed\typed-are-we-there-yet\node_modules\tape\bin\tape:31:13
    at Array.forEach (native)
    at D:\projects\typed\typed-are-we-there-yet\node_modules\tape\bin\tape:30:15
    at f (D:\projects\typed\typed-are-we-there-yet\node_modules\once\once.js:17:25)
````

I had the idea once to rewrite the `NodeJS.EventEmitter` interface as `EventEmitter<EventName extends string, Handler extends Function>{...}` but I had issues when I had multiple events.
I wasn't able to find a good example about dealing with `EventEmitter`'s types.

**Comment by blakeembrey** [comment]
You need to have a final definition that's a regular `string` (not a string literal) to be compatible, that's all.

**Comment by Demurgos** [comment]
Do you mean the following code would work ?
Would you link me to an example, I struggled with it for some time I just let it go so I'm really interested ?

````typescript
interface A extends NodeJS.EventEmitter {
  on(event: "change", listener: (name?: string, completed?: number, tracker?: TrackerGroup) => any): this;
}
interface B extends A {
  on(event: string, listener: (name?: string, completed?: number, tracker?: TrackerGroup) => any): this;
}
````

**Comment by blakeembrey** [comment]
Sure, I'm using it in `typings-core`: https://github.com/typings/core/blob/master/src/interfaces/emitter.ts#L9-L35.

**Comment by Demurgos** [comment]
Ok, now I understand why it works and why mine did not work. Thank you.

**Pull request merged**
