### PR TITLE
Create when.json

### PR DESCRIPTION
**Pull request by louy**
**Typings URL:** https://github.com/typed-typings/npm-when

**Questions (for new typings):**

* [x] Does the README explain the purpose and a link to the typed source?
* [x] Do the typings follow the source structure (e.g. `index.js` <-> `index.d.ts`)?
* [x] Are they correctly external or global modules?

### CODE REVIEW

**Comment by blakeembrey** [comment]
LGTM 👍 I think you could also use the `es6-promise` typings, if you wanted to make it consistent with other ES6 Promise typings implementations.

**Comment by louy** [comment]
I don't like the idea of using `es6-promise` for everything. It's not accurate at all and might allow someone to make mistakes. e.g. `when` doesn't have `Promise#race`

**Comment by blakeembrey** [comment]
@louy `Promise#race` is part of the spec for promises, so to be spec compatible I believe it would have it. I saw this: https://github.com/cujojs/when/blob/master/docs/api.md#whenrace.

**Comment by blakeembrey** [comment]
@louy If there's any inaccuracies in the typings though, definitely mention it.

**Pull request merged**
